import {assessReference} from './reference-assessment.js?v=20260921-basic2';
import {AUTHOR,DISCLAIMER} from './notice.js?v=20260921-basic2';
import {LABELS,RULE_LABELS} from './ai-core.js?v=20260921-basic2';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHTML;
const severity={problem:'需人工修正／核對',review:'待查證',info:'資訊'};
const safeLink=url=>/^https?:\/\//i.test(String(url))?e(url):'#';
export function reportHTML(report){
 const blocks=[],findings=report.findings||[],registry=report.registry||[],assessments=registry.map(assessReference),add=html=>blocks.push(html);
 const text=(label,value,cls='')=>{for(const chunk of String(value||'未提供').match(/[\s\S]{1,420}/g)||[])add(`<div class="detail ${cls}"><div class="field-label">${e(label)}</div><p>${e(chunk)}</p></div>`);};
 const section=(n,title)=>add(`<h2><span>${n}</span> ${e(title)}</h2>`);
 add(`<div class="cover"><div class="eyebrow">THESIS STUDIO · RESEARCH REVIEW</div><h1>論文檢查報告</h1><div class="document-name">${e(report.name)}</div><p class="cover-meta">${e(report.date)} ｜ ${e(report.provider||'基本檢查')} · ${e(report.model||'')}</p><div class="audit-only">僅查錯與排版 · 不更改統計數值 · 不改寫參考文獻</div></div>`);
 add(`<div class="metrics"><div><b>${registry.length}</b><span>文獻總數</span></div><div><b>${assessments.filter(a=>a.code==='ok').length}</b><span>OK · 基本書目</span></div><div><b class="danger">${assessments.filter(a=>a.code==='problem').length}</b><span>文獻有疑點</span></div><div><b class="amber">${assessments.filter(a=>!['ok','problem'].includes(a.code)).length}</b><span>其他待核對文獻</span></div></div>`);
 text('執行狀態',report.status,'status-box');
 section('01','逐篇文獻結論');
 text('判定範圍','OK 僅表示題名、第一作者、年份及原文有列出的 DOI 相符；不代表所有作者、卷期頁碼、引用樣式或全文主張正確。人工確認另行標示。查無紀錄不等於虛假；紅色粗體為需核對的疑點。');
 if(!registry.length)text('未執行資料庫查證','本次沒有逐篇資料庫結果。請先執行「基本檢查」的文獻查證；AI 意見不取代查證紀錄。');
 registry.forEach((r,i)=>{const a=assessments[i],cls=a.code==='problem'?'problem':a.code==='ok'?'info':'review',id='R'+String(i+1).padStart(3,'0');add(`<div class="index-row ${cls}"><b>${id}</b><span><strong>${e(a.label)} · 第 ${r.paragraph} 段</strong><br>${e((r.text.length>150?r.text.slice(0,150)+'…':r.text))}<br>${e(a.reasons.join(' '))}</span></div>`);});
 section('02','文獻判定依據');
 registry.forEach((r,i)=>{const a=assessments[i],cls=a.code==='problem'?'problem':a.code==='ok'?'info':'review';add(`<h3 class="issue-heading ${cls}">R${String(i+1).padStart(3,'0')} ｜ ${e(a.label)} ｜ 第 ${r.paragraph} 段</h3>`);text('原始書目（未修改）',r.text,cls+' evidence');text('結論與下一步',a.reasons.join(' '),cls);
 if(a.candidate){text('比對紀錄',`${a.source} ｜ ${a.candidate.title}\n${(a.candidate.authors||[]).join(', ')} ｜ ${a.candidate.year||'年份未提供'}\n${a.candidate.journal||''} ｜ DOI：${a.candidate.doi||'未提供'}`);text('欄位核對',Object.entries(a.fields).map(([k,v])=>({doi:'DOI',title:'題名',author:'第一作者',year:'年份'}[k])+': '+(v===null?'原文未列／不適用':v?'相符':'未確認相符')).join(' ｜ '));}
 if(a.url)add(`<p class="source"><a href="${safeLink(a.url)}">${e(a.source)}：開啟比對紀錄</a></p>`);
 const actual=(r.checks||[]).filter(c=>c.mode==='api');text('實際查詢紀錄',actual.map(c=>`${c.database}：${c.status} ｜ ${c.checkedAt||'尚未查詢'}`).join('\n')||'未執行自動查詢');
 for(const c of (r.checks||[]).filter(c=>c.manual)){text(c.database+' · 人工紀錄',`${c.manual.label}\n${c.manual.note}\n${c.manual.checkedAt} ｜ ${c.manual.origin}`,c.manual.status==='mismatch'?'problem':'');add(`<p class="source"><a href="${safeLink(c.manual.url)}">人工登錄的查證網址</a></p>`);}
 });
 section('03','其他檢查發現與處理建議');
 text('發現總覽',`${findings.length} 項：需核對 ${findings.filter(f=>f.severity==='problem').length}、待查證 ${findings.filter(f=>f.severity==='review').length}、資訊 ${findings.filter(f=>f.severity==='info').length}。下列依問題嚴重度排列，位置為段落編號，非 Word 頁碼。`);
 [...findings].sort((a,b)=>['problem','review','info'].indexOf(a.severity)-['problem','review','info'].indexOf(b.severity)).forEach((f,i)=>{const cls=f.severity==='problem'?'problem':f.severity==='review'?'review':'info';add(`<h3 class="${cls}">F${String(i+1).padStart(3,'0')} · ${e(LABELS[f.category])} · ${e(severity[f.severity])}</h3>`);text('位置與原文證據',f.location+'\n'+f.evidence,cls+' evidence');text('原因與人工處理',f.explanation+'\n建議：'+f.suggestion);text('判讀來源',f.origin||'AI 判讀，須人工審閱','muted');});
 if(report.rules?.length){section('04','可採用的排版建議');for(const r of report.rules)text(`${RULE_LABELS[r.key]||r.key}：${r.value}`,r.evidence);}
 if(report.summaries?.length){section('05','AI 摘要（需人工覆核）');report.summaries.forEach((s,i)=>text('批次 '+(i+1),s));}
 if(report.externalReview){section('06','RefCheck 匯入紀錄');text('來源與時間',`${report.externalReview.source} ｜ ${report.externalReview.importedAt}\n${report.externalReview.origin}`);text('原樣保留；未自動配對或判定通過',report.externalReview.text);}
 section('07','範圍、方法與責任');
 for(const c of report.coverage||[])text('本次檢查範圍',c);
 text('使用紀錄',report.planned?`AI：${report.provider} / ${report.model}；完成 ${report.completed}/${report.planned} 批。輸入 ${report.inputTokens} tokens、輸出 ${report.outputTokens} tokens。模組：${(report.tasks||[]).map(x=>LABELS[x]).join('、')}。引用格式：${(report.styles||[]).join('、')||'未檢查'}。`:'本次未執行 AI；不需 AI API Key。若有文獻查詢，僅將 DOI／書目傳送至所選資料庫；統計規則在本機執行。');
 text('限制與作者責任','書目基本比對不是全文或學術誠信認證。資料庫可能共用紀錄，收錄與查詢也可能不完整。所有紅色或粗體疑點須由作者核對；不得據此認定虛假文獻或學術不端。統計只能檢查可抽取文字的一致性，無法驗證原始資料；任何計算均不能作為替換數值。請依學校與期刊規定揭露 AI 使用，保留原稿及查核紀錄。');
 add('<p class="source">倫理參考：<a href="https://doi.org/10.24318/cCVRZBms">COPE</a>；<a href="https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research">UNESCO</a>。<a href="https://www.ncbi.nlm.nih.gov/About/disclaimer.html">NCBI 使用聲明</a>。未操作的人工查證入口不列為已查閱來源。</p>');
 text('網站作者',AUTHOR);text('免責聲明',DISCLAIMER);
 return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>論文完稿室｜檢查報告</title><style>${REPORT_CSS}</style></head><body><main id="report-flow">${blocks.map(b=>`<div class="report-block">${b}</div>`).join('')}</main></body></html>`;
}
export const REPORT_CSS=`*{box-sizing:border-box}body{margin:0;background:#eaf0ed;color:#253c35;font:14px/1.75 Arial,"Microsoft JhengHei",sans-serif}#report-flow{max-width:794px;margin:24px auto;padding:42px 46px;background:#fff}.cover{background:#143e32;color:#fff;padding:30px 28px;border-top:6px solid #c0a46e}.eyebrow{font-size:10px;letter-spacing:2px;color:#c4d9cf}h1{font-size:29px;line-height:1.3;margin:18px 0 10px}.subtitle{color:#d1e0d8;font-size:13px}.document-name{font-size:19px;font-weight:700;margin-top:24px;overflow-wrap:anywhere}.cover-meta{font-size:11px;color:#ccded4}.audit-only{border-top:1px solid #587d6b;margin-top:20px;padding-top:14px;font-size:12px;font-weight:700}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #d5e3db;margin:20px 0}.metrics>div{padding:15px 8px;text-align:center;border-right:1px solid #d5e3db}.metrics>div:last-child{border:0}.metrics b{display:block;font-size:25px;line-height:1.5}.metrics span{font-size:10px;color:#5d7267}.danger{color:#ad2034}.amber{color:#865618}h2{font-size:20px;border-bottom:2px solid #244e3b;padding:15px 0 9px;margin:22px 0 10px}h2 span{color:#62816d;font-size:14px;margin-right:10px}h3{font-size:16px;margin:18px 0 0;padding:12px 14px;background:#edf4ef;line-height:1.6}.section-note,.source{font-size:11px;color:#63776b}.detail{padding:10px 14px;border-left:3px solid #d3e1d8;margin:0 0 5px;background:#fafcfb}.field-label{font-size:11px;font-weight:700;color:#597164;margin-bottom:4px}.detail p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.problem{color:#a21f30;border-color:#b6273b;background:#fff3f3}.problem p,.problem strong{font-weight:700}.review{color:#815515;border-color:#ae853e;background:#fffaf0}.review p{font-weight:700}.info{border-color:#618871}.muted{font-size:12px;color:#607369}.status-box{border-color:#1b6547}.issue-id{display:inline-block;margin-right:8px;font-size:12px}.index-row{display:flex;gap:15px;padding:10px 14px;border-left:3px solid #c9dbd0;margin-bottom:6px;line-height:1.65}.index-row>b{min-width:30px}.index-row span{overflow-wrap:anywhere;font-size:12px}a{color:#185a43;overflow-wrap:anywhere}p{overflow-wrap:anywhere}.report-block{break-inside:avoid}.report-page{width:794px;height:1123px;padding:42px 46px 55px;background:white;position:relative;overflow:hidden}.page-content{height:100%;overflow:hidden}.report-footer{position:absolute;bottom:19px;left:46px;right:46px;display:flex;justify-content:space-between;font-size:10px;color:#658070;border-top:1px solid #d6e3dc;padding-top:8px}@page{size:A4;margin:0}@media print{body{background:#fff}#report-flow{margin:0;padding:42px;width:100%;max-width:none}h2,h3{break-after:avoid}.report-page{break-after:page}.report-page:last-child{break-after:auto}}@media(max-width:600px){#report-flow{margin:0;padding:18px}.metrics{grid-template-columns:repeat(2,1fr)}}`;

export async function exportPDF(html,progress=()=>{}){
  const frame=document.createElement('iframe');frame.style.cssText='position:fixed;left:-10000px;top:0;width:820px;height:1200px;border:0';document.body.append(frame);
  try{await new Promise(resolve=>{frame.onload=resolve;frame.srcdoc=html;});const doc=frame.contentDocument;await doc.fonts.ready;const blocks=[...doc.querySelectorAll('.report-block')];doc.body.replaceChildren();let page,content;
    function newPage(){page=doc.createElement('section');page.className='report-page';content=doc.createElement('div');content.className='page-content';page.append(content);doc.body.append(page);}
    newPage();for(const block of blocks){content.append(block);if(content.scrollHeight>content.clientHeight+1){block.remove();if(!content.children.length)throw Error('報告有單一項目過長，請下載 HTML 報告後列印為 PDF。');const headings=[];while(content.lastElementChild?.firstElementChild?.matches('h1,h2,h3'))headings.unshift(content.lastElementChild),content.lastElementChild.remove();newPage();content.append(...headings,block);if(content.scrollHeight>content.clientHeight+1)throw Error('報告項目超出頁面，請使用 HTML 報告列印。');}}
    const pages=[...doc.querySelectorAll('.report-page')],pdf=await PDFLib.PDFDocument.create();pdf.setTitle('論文完稿室｜詳細分析報告');pdf.setSubject('AI analysis with source verification and coverage');for(let i=0;i<pages.length;i++){const footer=doc.createElement('div');footer.className='report-footer';footer.innerHTML=`<span>論文完稿室｜檢查與查證紀錄</span><span>${i+1} / ${pages.length}</span>`;pages[i].append(footer);progress(`正在匯出 PDF：${i+1} / ${pages.length} 頁`);const canvas=await html2canvas(pages[i],{scale:1.5,backgroundColor:'#ffffff',logging:false,windowWidth:820,windowHeight:1200});const img=await pdf.embedPng(canvas.toDataURL('image/png'));const p=pdf.addPage([595.28,841.89]);p.drawImage(img,{x:0,y:0,width:595.28,height:841.89});canvas.width=1;canvas.height=1;await new Promise(resolve=>setTimeout(resolve,0));}return new Blob([await pdf.save()],{type:'application/pdf'});
  }finally{frame.remove();}
}
