import {AUTHOR,DISCLAIMER} from './notice.js?v=20260921-notice1';
import {LABELS,RULE_LABELS} from './ai-core.js?v=20260921-notice1';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escapeHTML;
const severity={problem:'需修正',review:'待確認',info:'資訊'};
function paragraphs(text){const chunks=String(text||'').match(/[\s\S]{1,650}/g)||['—'];return chunks.map(x=>`<p>${e(x)}</p>`).join('');}
export function reportHTML(report){let blocks=[];const add=(title,text)=>{blocks.push(`<h2>${e(title)}</h2>`);for(const html of paragraphs(text).match(/<p>[\s\S]*?<\/p>/g)||[])blocks.push(html);};
  blocks.push('<h1>論文進階檢查報告</h1>');add('分析資訊',`論文：${report.name}\n產生時間：${report.date}\n模型：${report.model}\n參考文獻目標格式：${report.targetStyle}\n選取模組：${report.tasks.map(x=>LABELS[x]).join('、')}\n執行狀態：${report.status}`);
  add('檢查範圍與完成度',report.coverage.join('\n'));add('結果摘要',`檢核發現 ${report.findings.length} 項；參考文獻查詢 ${report.registry.length} 筆；可審閱的書目修訂 ${report.edits.length} 筆。\n${report.summaries.join('\n')}`);
  for(const category of report.tasks){blocks.push(`<h2>${e(LABELS[category])}</h2>`);const items=report.findings.filter(x=>x.category===category);if(!items.length)blocks.push('<p>此模組沒有回傳可列出的發現。這不代表全部符合，請參照完成度與限制。</p>');items.forEach((f,i)=>{blocks.push(`<h3>${i+1}. ${e(severity[f.severity]||'待確認')}｜${e(f.location)}</h3>`);blocks.push(`<p class="source">來源：${e(f.origin||'AI 判讀，須人工審閱')}</p>`);for(const [title,text]of [['證據',f.evidence],['判讀',f.explanation],['建議',f.suggestion]])for(const chunk of String(text||'—').match(/[\s\S]{1,650}/g)||[])blocks.push(`<p><b>${title}：</b>${e(chunk)}</p>`);});}
  if(report.rules.length){blocks.push('<h2>AI 擷取的格式要求</h2>');for(const r of report.rules)add(`${RULE_LABELS[r.key]||r.key}：${r.value}`,`原文依據：${r.evidence}`);}
  if(report.registry.length){blocks.push('<h2>文獻查證紀錄</h2>');report.registry.forEach((r,i)=>{blocks.push(`<h3>${i+1}. 第 ${r.paragraph} 段｜${e(r.status)}</h3>`);blocks.push(...paragraphs(r.text).match(/<p>[\s\S]*?<\/p>/g));blocks.push(`<p class="source">查詢方法：${e(r.method)}<br>時間：${e(r.checkedAt)}<br><a href="${e(r.source)}">Crossref 查詢紀錄</a></p>`);for(const c of r.candidates){blocks.push(...paragraphs(`候選紀錄：${c.title}\n${c.authors.join(', ')} (${c.year??'—'}) · ${c.journal}\nDOI：${c.doi}\n${c.url}\n僅確認資料庫紀錄，不代表論文引用的主張已獲全文支持。`).match(/<p>[\s\S]*?<\/p>/g));if(c.updates?.length)blocks.push(`<p>Crossref 更新關聯：${e(JSON.stringify(c.updates))}。需查看更新內容，不能直接推定本篇已撤稿。</p>`);}});}
  if(report.edits.length){blocks.push('<h2>參考文獻格式修訂建議</h2>');if(report.targetStyle==='APA 7')blocks.push('<p>下載修訂 Word 時可勾選：同時套用 APA 7 懸掛縮排 1.27 公分、雙倍行距。若學校另有規範可取消；本報告列的是建議，並非已套用紀錄。</p>');report.edits.forEach((r,i)=>{blocks.push(`<h3>${i+1}. 第 ${r.paragraph} 段 · ${e(report.targetStyle)}</h3>`);add('修改前',r.before);add('修改後（尚未自動套用）',r.after);add('理由',r.reason);});}
  add('限制與使用說明','AI 可能判讀錯誤。Crossref 未找到紀錄、沒有 DOI 或查詢失敗，均不能證明文獻虛假；資料庫紀錄存在也不等於題名、作者與本文主張正確。未取得來源全文時，無法確認引用是否忠實。統計檢查只核對本文敘述與可解析的數值；無原始資料不能驗證分析過程、假設、資料品質或研究結論。此報告不代表學校認證、學術不端認定或完整的文獻系統性查證。');
  add('網站作者',AUTHOR);add('免責聲明',DISCLAIMER);
  add('傳輸與用量',`選取的資料已由瀏覽器送到 OpenAI；查證所需的書目文字或 DOI 送到 Crossref。未將 API Key 存入報告或網站儲存空間。\nAPI 請求完成 ${report.completed} / ${report.planned} 批；累計輸入 ${report.inputTokens} tokens、輸出 ${report.outputTokens} tokens（以服務回傳資訊為準，不是費用報價）。`);
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>論文進階檢查報告</title><style>${REPORT_CSS}</style></head><body><main id="report-flow">${blocks.map(b=>`<div class="report-block">${b}</div>`).join('')}</main></body></html>`;
}
export const REPORT_CSS=`*{box-sizing:border-box}body{margin:0;background:#edf1f0;color:#203b32;font:15px/1.8 Arial,"Microsoft JhengHei",sans-serif}#report-flow{max-width:794px;margin:24px auto;padding:48px;background:white}h1{font:700 28px Arial,"Microsoft JhengHei",sans-serif;color:#174d3c;margin:0 0 20px}h2{font-size:19px;line-height:1.5;border-bottom:1px solid #c8dad0;padding-bottom:7px;margin:20px 0 12px;color:#174d3c}h3{font-size:16px;line-height:1.6;margin:14px 0 8px}p{white-space:pre-wrap;margin:7px 0;overflow-wrap:anywhere}.source{font-size:12px;color:#60796b}a{color:#18594c;overflow-wrap:anywhere}.report-block{break-inside:avoid}.report-page{width:794px;height:1123px;padding:46px 48px 52px;background:white;position:relative;overflow:hidden}.page-content{height:100%;overflow:hidden}.report-footer{position:absolute;bottom:20px;left:48px;right:48px;display:flex;justify-content:space-between;font-size:11px;color:#658070;border-top:1px solid #d6e3dc;padding-top:7px}@page{size:A4;margin:0}@media print{body{background:white}#report-flow{margin:0;padding:45px;width:100%;max-width:none}.report-page{break-after:page}.report-page:last-child{break-after:auto}}`;
export async function exportPDF(html,progress=()=>{}){
  const frame=document.createElement('iframe');frame.style.cssText='position:fixed;left:-10000px;top:0;width:820px;height:1200px;border:0';document.body.append(frame);
  try{await new Promise(resolve=>{frame.onload=resolve;frame.srcdoc=html;});const doc=frame.contentDocument;await doc.fonts.ready;const blocks=[...doc.querySelectorAll('.report-block')];doc.body.replaceChildren();let page,content;
    function newPage(){page=doc.createElement('section');page.className='report-page';content=doc.createElement('div');content.className='page-content';page.append(content);doc.body.append(page);}
    newPage();for(const block of blocks){content.append(block);if(content.scrollHeight>content.clientHeight+1){block.remove();if(!content.children.length)throw Error('報告有單一項目過長，請下載 HTML 報告後列印為 PDF。');const headings=[];while(content.lastElementChild?.firstElementChild?.matches('h1,h2,h3'))headings.unshift(content.lastElementChild),content.lastElementChild.remove();newPage();content.append(...headings,block);if(content.scrollHeight>content.clientHeight+1)throw Error('報告項目超出頁面，請使用 HTML 報告列印。');}}
    const pages=[...doc.querySelectorAll('.report-page')],pdf=await PDFLib.PDFDocument.create();pdf.setTitle('論文進階檢查報告');pdf.setSubject('AI analysis with source verification and coverage');for(let i=0;i<pages.length;i++){const footer=doc.createElement('div');footer.className='report-footer';footer.innerHTML=`<span>論文整稿室｜AI 判讀與查證紀錄</span><span>${i+1} / ${pages.length}</span>`;pages[i].append(footer);progress(`正在匯出 PDF：${i+1} / ${pages.length} 頁`);const canvas=await html2canvas(pages[i],{scale:1.5,backgroundColor:'#ffffff',logging:false,windowWidth:820,windowHeight:1200});const img=await pdf.embedPng(canvas.toDataURL('image/png'));const p=pdf.addPage([595.28,841.89]);p.drawImage(img,{x:0,y:0,width:595.28,height:841.89});canvas.width=1;canvas.height=1;await new Promise(resolve=>setTimeout(resolve,0));}return new Blob([await pdf.save()],{type:'application/pdf'});
  }finally{frame.remove();}
}
