import {getBasicReport} from './basic-ui.js?v=20260921-format5';
import {getAIContext,setAILock,applyAIRules} from './app.js?v=20260921-format5';
import {PROVIDERS,LABELS,RULE_LABELS,referenceStart,referenceRows,batches,requestAnalysis,checkGeminiModel,listGeminiModels} from './ai-core.js?v=20260921-format5';
import {reportHTML,exportPDF} from './ai-report.js?v=20260921-format5';
const $=s=>document.querySelector(s),dialog=$('#ai-dialog');let externalReview=null,selectionDoc=null,controller=null,report=null,snapshot=null,viewPage=0,selectedRules=new Set();
function message(text,error=false){$('#ai-status').textContent=text;$('#ai-status').classList.toggle('error',error);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function providerInfo(){return PROVIDERS[$('#ai-provider').value];}
let modelCheck=null,modelListTask=null;
function updateProvider(){resetModelList();modelCheck?.abort();$('#gemini-check').hidden=$('#ai-provider').value!=='gemini';$('#gemini-check-status').hidden=true;const selected=providerInfo();$('#ai-key-label').textContent=selected.label+' API Key';$('#ai-disclosure').textContent=`AI 模組會將所需的規範、論文文字及書目傳送至 ${selected.label}。資料庫查證與統計規則檢查請使用「基本檢查」，不需要 AI 金鑰。使用可能產生所選供應商的 API 費用，資料處理依其服務條款。金鑰僅在本次頁面記憶體中使用，不儲存；切換供應商或關閉視窗會清除。請在可信任的電腦與瀏覽器使用。文獻查不到不等於虛假，引用主張需全文確認；統計檢查無法取代原始資料重算。`;}
$('#ai-provider').addEventListener('change',()=>{$('#ai-key').value='';$('#ai-consent').checked=false;$('#ai-model').value=providerInfo().model;updateProvider();message('已切換供應商並清除金鑰，請輸入對應金鑰並重新確認資料傳送。');});updateProvider();
function styles(){return[...document.querySelectorAll('[name=ai-style]:checked')].map(el=>el.value);}
function tasks(){return[...document.querySelectorAll('[name=ai-task]:checked')].map(el=>el.value);}
function showTab(tab){for(const el of document.querySelectorAll('[data-ai-panel]'))el.hidden=el.dataset.aiPanel!==tab;for(const el of document.querySelectorAll('[data-ai-tab]'))el.setAttribute('aria-pressed',String(el.dataset.aiTab===tab));}
for(const el of document.querySelectorAll('[data-ai-tab]'))el.addEventListener('click',()=>showTab(el.dataset.aiTab));
$('#open-ai').addEventListener('click',()=>{const ctx=getAIContext(),select=$('#ai-ref-start');const previous=select.value;select.replaceChildren(new Option('未辨識／不分析參考文獻區段','-1'));if(ctx.thesis){for(const p of ctx.thesis.info.paragraphs.filter(x=>x.text.trim()))select.add(new Option(`${p.index+1} · ${p.text.slice(0,65)}`,String(p.index)));select.value=selectionDoc===ctx.thesis&&previous&&[...select.options].some(x=>x.value===previous)?previous:String(referenceStart(ctx.thesis.info.paragraphs));}selectionDoc=ctx.thesis;dialog.showModal();estimate();});
$('#ai-close').addEventListener('click',()=>{modelCheck?.abort();if(controller){message('分析進行中，請先按「取消分析」。');return;}$('#ai-key').value='';dialog.close();});dialog.addEventListener('cancel',e=>{if(controller){e.preventDefault();message('分析進行中，請先取消分析。');}else $('#ai-key').value='';});
$('#ai-enabled').addEventListener('change',()=>{if(!$('#ai-enabled').checked){$('#ai-key').value='';controller?.abort();}$('#ai-options').disabled=!$('#ai-enabled').checked;});
$('#ai-clear-key').addEventListener('click',()=>{$('#ai-key').value='';message('金鑰已清除。');});
$('#ai-cancel').addEventListener('click',()=>controller?.abort());
document.addEventListener('thesis-context-changed',()=>{controller?.abort();report=null;externalReview=null;snapshot=null;selectionDoc=null;viewPage=0;selectedRules.clear();render();});
function estimate(){const ctx=getAIContext(),selected=tasks();const total=ctx.thesis?.info.paragraphs.reduce((n,p)=>n+p.text.length,0)||0;$('#ai-coverage').textContent=ctx.thesis?`論文 ${ctx.thesis.info.paragraphs.length} 段、約 ${total.toLocaleString()} 字元。${selected.includes('citations')||selected.includes('statistics')?'本文會分批送交 AI 分析。':'只傳送勾選模組需要的規範或書目內容。'} 各模組可分別執行。統計與引用僅查錯，不改寫文字或數值。`:'請先在工作台上傳論文；若要分析規範，也請先載入規範。';}
document.querySelectorAll('[name=ai-task],[name=ai-style],#ai-ref-start').forEach(el=>el.addEventListener('change',estimate));
function safeRules(rules,text){const ranges={top:[0,10],bottom:[0,10],left:[0,10],right:[0,10],size:[6,72],line:[.5,4]},normalize=s=>s.normalize('NFKC').replace(/\s/g,'');const result=[];for(const r of rules){if(!r.evidence||!normalize(text).includes(normalize(r.evidence)))continue;if(r.key in ranges){const v=+r.value,[min,max]=ranges[r.key];if(!Number.isFinite(v)||v<min||v>max)continue;}else if(r.key==='paper'&&!['A4','Letter'].includes(r.value)||r.key==='color'&&r.value!=='黑色'||r.key==='page'&&r.value!=='頁尾置中'||['cjk','latin'].includes(r.key)&&r.value.length>80)continue;if(!['paper','top','bottom','left','right','cjk','latin','size','line','color','page'].includes(r.key))continue;result.push(r);}return result.filter((r,_,all)=>all.filter(x=>x.key===r.key).every(x=>x.value===r.value)).filter((r,i,all)=>all.findIndex(x=>x.key===r.key)===i);}
async function analyze(){if(controller)return;const provider=$('#ai-provider').value;const ctx=getAIContext(),selected=tasks(),selectedStyles=styles(),targetStyle=$('#ai-target-style').value;
  if(!$('#ai-enabled').checked)throw Error('請先勾選 AI 進階分析。');if(!ctx.thesis)throw Error('請先上傳 Word 論文。');if(selected.includes('requirements')&&!ctx.requirements)throw Error('請先載入學校格式規範。');if(!selected.length)throw Error('請至少勾選一個分析模組。');if(selected.includes('references')&&(!selectedStyles.length||!selectedStyles.includes(targetStyle)))throw Error('請勾選要檢查的引用格式，並將主要檢查標準設為其中一種。');let key=$('#ai-key').value.trim();if(!key||/\s/.test(key))throw Error(`請輸入有效的 ${providerInfo().label} API Key。`);if(!$('#ai-consent').checked)throw Error('請閱讀並勾選資料傳送與費用說明。');const model=$('#ai-model').value.trim();if(!/^[a-zA-Z0-9._:-]+$/.test(model))throw Error('模型名稱格式不正確。');
  const paragraphs=ctx.thesis.info.paragraphs,refs=referenceRows(paragraphs,Number($('#ai-ref-start').value));if((selected.includes('references')||selected.includes('citations'))&&!refs.length)throw Error('請指定參考文獻標題所在段落，確認其後有文獻內容。');if(refs.length>200)throw Error('目前單次支援最多 200 個書目段落，請使用分章文件分析。');if(paragraphs.reduce((n,p)=>n+p.text.length,0)>300000)throw Error('目前單次支援 30 萬字元，請先將論文分章後分析。');if((ctx.requirements?.text.length||0)>60000&&selected.includes('requirements'))throw Error('格式規範超過 6 萬字元，請擷取論文相關部分再上傳。');
  const body=paragraphs.filter(p=>p.index<=Number($('#ai-ref-start').value)||Number($('#ai-ref-start').value)<0);const jobs=[];
  if(selected.includes('requirements'))jobs.push({tasks:['requirements'],requirements:ctx.requirements.text,notes:'Analyze the school requirements and extract only supported rules. Do not claim actual layout compliance: this task receives requirements, not rendered pages.'});
  if(selected.includes('references'))for(const group of batches(refs.map(r=>({index:r.paragraph-1,text:r.text})),9000))jobs.push({tasks:['references'],paragraphs:group,styles:selectedStyles,targetStyle});
  const bodyTasks=selected.filter(x=>['citations','statistics'].includes(x));if(bodyTasks.length)for(const group of batches(body))jobs.push({tasks:bodyTasks,paragraphs:group,notes:'Only this batch of extracted text is supplied. Equations in images, visual table layout and raw data are not supplied. Check citation correspondence and statistical reporting with these limits.'});
  controller=new AbortController();setAILock(true);$('#ai-options').disabled=true;$('#ai-run').disabled=true;$('#ai-cancel').disabled=false;$('#ai-key').value='';snapshot=ctx;viewPage=0;selectedRules.clear();report={externalReview,name:ctx.thesis.name,date:new Date().toLocaleString('zh-TW'),provider:PROVIDERS[provider].label,model,targetStyle,styles:selectedStyles,tasks:selected,status:'分析中',findings:structuredClone(getBasicReport()?.findings||[]),rules:[],registry:structuredClone(getBasicReport()?.registry||[]),summaries:[],coverage:[`抽取 ${paragraphs.length} 個段落；書目區段 ${refs.length} 個非空段落。書目以每段為一筆查詢，跨段文獻需人工合併確認。`,`預計 ${jobs.length} 個 AI 批次。圖片內文字與公式圖像不在分析範圍。`],completed:0,planned:jobs.length,inputTokens:0,outputTokens:0};render();
  try{
    report.coverage.push(...(getBasicReport()?.coverage||[]).map(x=>'基本檢查：'+x));
    report.coverage.push(report.registry.length?'附上已完成的基本查證紀錄；AI 不會重新查詢資料庫。':'尚未執行基本文獻查證。AI 判讀不等於資料庫查證；請另至基本檢查逐篇核對。');
    for(let i=0;i<jobs.length;i++){controller.signal.throwIfAborted();const job=jobs[i];message(`AI 分析 ${i+1} / ${jobs.length}：${job.tasks.map(x=>LABELS[x]).join('、')}…`);const ids=new Set(job.paragraphs?.map(p=>p.paragraph));const registry=job.tasks.includes('requirements')?[]:report.registry.filter(r=>job.tasks.includes('references')?ids.has(r.paragraph):true).map(r=>({paragraph:r.paragraph,original:r.text,status:r.status,sources:r.checks.map(c=>({database:c.database,mode:c.mode,status:c.status,checkedAt:c.checkedAt,source:c.source})),candidates:r.checks.flatMap(c=>c.candidates.slice(0,1).map(item=>({...item,database:c.database}))).map(c=>({...c,abstract:job.tasks.includes('citations')?c.abstract.slice(0,2500):''}))}));
      const result=await requestAnalysis({provider,key,model,signal:controller.signal,payload:{...job,registry,totalBatches:jobs.length,batchNumber:i+1}});report.completed++;report.inputTokens+=result.usage.input_tokens||0;report.outputTokens+=result.usage.output_tokens||0;report.summaries.push(result.summary);report.findings.push(...result.findings.filter(f=>job.tasks.includes(f.category)).map(f=>({...f,origin:'AI 判讀，須人工審閱'})));if(job.tasks.includes('requirements'))report.rules=safeRules(result.rules,ctx.requirements.text);
      report.coverage.push(`完成批次 ${i+1}：${job.tasks.map(x=>LABELS[x]).join('、')}${job.paragraphs?`，第 ${job.paragraphs[0].paragraph}–${job.paragraphs.at(-1).paragraph} 段`:''}。`);render();
    }report.status=report.registry.some(r=>r.checks.some(c=>c.outcome==='error'))?'AI 批次已完成，部分外部查證失敗':'所選 AI 批次已完成（仍有待確認項目）';message('分析完成。請查看檢核結果與格式建議，並下載報告。');showTab('findings');
  }catch(e){report.failure=e.name==='AbortError'?'使用者取消':e.message;report.status=e.name==='AbortError'?'已取消，這是部分結果':'未全部完成，這是部分結果';report.coverage.push('未完成原因：'+(e.name==='AbortError'?'使用者取消':e.message));message(report.status+'：'+(e.name==='AbortError'?'可下載已完成部分的報告。':e.message),true);showTab('findings');}finally{key='';controller=null;setAILock(false);$('#ai-options').disabled=!$('#ai-enabled').checked;$('#ai-run').disabled=false;$('#ai-cancel').disabled=true;render();}
}
$('#ai-run').addEventListener('click',()=>analyze().catch(e=>message(e.message,true)));
function pageItems(){if(!report)return[];const category=$('#ai-filter').value;return report.findings.filter(f=>category==='all'||f.category===category);}
function render(){const available=!!report&&!controller;for(const id of ['#ai-html','#ai-pdf'])$(id).disabled=!available;$('#ai-report-state').textContent=report?`${report.status} · 完成 ${report.completed}/${report.planned} 批 · ${report.findings.length} 項發現 · ${report.registry.length} 筆查證${report.failure?' · '+report.failure:''}`:'尚未分析';const items=pageItems(),pages=Math.max(1,items.length);viewPage=Math.min(viewPage,pages-1);$('#ai-findings').replaceChildren();for(const f of items.slice(viewPage,viewPage+1)){const card=document.createElement('li');const title=document.createElement('strong');title.textContent=`${viewPage+1}. ${LABELS[f.category]} · ${f.severity==='problem'?'需修正':f.severity==='review'?'待確認':'資訊'} · ${f.location}`;card.dataset.severity=f.severity;card.append(title);for(const [label,text]of [['證據',f.evidence],['判讀',f.explanation],['建議',f.suggestion]]){const p=document.createElement('p');p.textContent=label+'：'+text;card.append(p);}$('#ai-findings').append(card);}if(!items.length)$('#ai-findings').textContent=report?'目前沒有此類檢核發現；請查看報告的完成度。':'啟用 AI 並選擇模組後，開始分析。';$('#ai-page').textContent=`${viewPage+1} / ${pages} 頁`;$('#ai-prev').disabled=viewPage===0;$('#ai-next').disabled=viewPage===pages-1;
  $('#ai-rule-list').replaceChildren();for(const [i,r]of (report?.rules||[]).entries()){const label=document.createElement('label');label.className='ai-rule';const input=document.createElement('input');input.type='checkbox';input.checked=selectedRules.has(i);input.disabled=!!controller;input.addEventListener('change',()=>{input.checked?selectedRules.add(i):selectedRules.delete(i);$('#ai-use-rules').disabled=!selectedRules.size||!!controller;});label.append(input,document.createTextNode(` ${RULE_LABELS[r.key]||r.key}：${r.value}；依據：${r.evidence}`));$('#ai-rule-list').append(label);}$('#ai-use-rules').disabled=!selectedRules.size||!!controller;
}
$('#ai-filter').addEventListener('change',()=>{viewPage=0;render();});$('#ai-prev').addEventListener('click',()=>{viewPage--;render();});$('#ai-next').addEventListener('click',()=>{viewPage++;render();});
$('#ai-html').addEventListener('click',()=>{if(report)download(new Blob([reportHTML(report)],{type:'text/html;charset=utf-8'}),'論文AI檢查報告.html');});
$('#ai-pdf').addEventListener('click',async()=>{if(!report)return;$('#ai-pdf').disabled=true;try{download(await exportPDF(reportHTML(report),text=>message(text)),'論文AI檢查報告.pdf');message('PDF 報告已下載。另提供可搜尋、可列印的 HTML 版本。');}catch(e){message(e.message,true);}finally{$('#ai-pdf').disabled=false;}});
$('#ai-use-rules').addEventListener('click',()=>{if(!report||!snapshot)return;applyAIRules([...selectedRules].map(i=>report.rules[i]));message('已將勾選的格式建議填入工作台。仍需在工作台預覽並確認套用。');});

window.addEventListener('pagehide',()=>{$('#ai-key').value='';controller?.abort();});render();

document.addEventListener('refcheck-imported',e=>{externalReview=e.detail;if(report)report.externalReview=externalReview;});

$('#gemini-check').addEventListener('click',async()=>{
 if(modelCheck)return;modelCheck=new AbortController();const task=modelCheck;$('#gemini-check').disabled=true;$('#gemini-check-status').hidden=false;$('#gemini-check-status').textContent='正在向 Google 查詢模型資訊；不傳送論文…';
 try{const text=await checkGeminiModel({key:$('#ai-key').value.trim(),model:$('#ai-model').value.trim(),signal:task.signal});if(!task.signal.aborted)$('#gemini-check-status').textContent=text;}
 catch(err){if(!task.signal.aborted)$('#gemini-check-status').textContent=err.message;}
 finally{modelCheck=null;$('#gemini-check').disabled=false;}
});
$('#ai-key').addEventListener('input',()=>{$('#gemini-check-status').hidden=true;modelCheck?.abort();});
$('#ai-model').addEventListener('input',()=>{$('#gemini-check-status').hidden=true;modelCheck?.abort();});
$('#ai-clear-key').addEventListener('click',()=>{modelCheck?.abort();$('#gemini-check-status').hidden=true;});
dialog.addEventListener('cancel',()=>modelCheck?.abort());
window.addEventListener('pagehide',()=>modelCheck?.abort());

function resetModelList(){modelListTask?.abort();$('#gemini-model-tools').hidden=$('#ai-provider').value!=='gemini';$('#gemini-model-list').replaceChildren(new Option('請先輸入金鑰，再載入清單',''));$('#gemini-model-list').disabled=true;$('#gemini-model-status').textContent='清單由 Google 即時回傳，不保證生成額度、存取權限或結構化輸出支援；不傳送論文。';}
$('#gemini-load-models').addEventListener('click',async()=>{
 if(modelListTask)return;const task=new AbortController();modelListTask=task;$('#gemini-load-models').disabled=true;$('#gemini-model-list').disabled=true;$('#gemini-model-list').replaceChildren(new Option('正在載入完整清單…',''));$('#gemini-model-status').textContent='正在取得所有分頁的模型名稱…';
 try{const rows=await listGeminiModels({key:$('#ai-key').value.trim(),signal:task.signal});if(task.signal.aborted)return;const list=$('#gemini-model-list');list.replaceChildren(new Option('請選擇模型（不會自動更換目前模型）',''));let count=0;for(const row of rows){const supported=row.methods.includes('generateContent');const option=new Option(row.id+' · '+row.label+(supported?'':'（不支援本系統生成方法）'),row.id);option.disabled=!supported;list.add(option);if(supported)count++;}list.disabled=!count;$('#gemini-model-status').textContent=`已載入 ${rows.length} 個模型，其中 ${count} 個支援 generateContent。清單不保證文字／結構化輸出相容性與額度；請選一般文字模型，避免 image、tts、audio 等專用模型。`;}
 catch(err){if(!task.signal.aborted){$('#gemini-model-list').replaceChildren(new Option('載入失敗，請重試',''));$('#gemini-model-status').textContent=err.message;}}
 finally{modelListTask=null;$('#gemini-load-models').disabled=false;}
});
$('#gemini-model-list').addEventListener('change',()=>{if($('#gemini-model-list').value){$('#ai-model').value=$('#gemini-model-list').value;$('#ai-model').dispatchEvent(new Event('input'));}});
for(const id of ['#ai-key','#ai-clear-key','#ai-close'])$(id).addEventListener(id==='#ai-key'?'input':'click',resetModelList);
dialog.addEventListener('cancel',resetModelList);
$('#ai-enabled').addEventListener('change',()=>{if(!$('#ai-enabled').checked)resetModelList();});
window.addEventListener('pagehide',resetModelList);
