import {DATABASES,verifySources,saveManualCheck} from './sources.js?v=20260921-refcheck1';
import {getAIContext,setAILock,applyAIRules} from './app.js?v=20260921-refcheck1';
import {PROVIDERS,LABELS,RULE_LABELS,referenceStart,referenceRows,batches,requestAnalysis,checkStatistics} from './ai-core.js?v=20260921-refcheck1';
import {reportHTML,exportPDF} from './ai-report.js?v=20260921-refcheck1';
const $=s=>document.querySelector(s),dialog=$('#ai-dialog');let externalReview=null,selectionDoc=null,controller=null,report=null,snapshot=null,viewPage=0,selectedRules=new Set();
function message(text,error=false){$('#ai-status').textContent=text;$('#ai-status').classList.toggle('error',error);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function providerInfo(){return PROVIDERS[$('#ai-provider').value];}
function updateProvider(){const selected=providerInfo();$('#ai-key-label').textContent=selected.label+' API Key';$('#ai-disclosure').textContent=`AI 模組會將所需的規範、論文文字及書目傳送至 ${selected.label}；DOI／書目依勾選來源送至 Crossref、OpenAlex、PubMed。使用可能產生所選供應商的 API 費用，資料處理依其服務條款。金鑰僅在本次頁面記憶體中使用，不儲存；切換供應商或關閉視窗會清除。請在可信任的電腦與瀏覽器使用。文獻查不到不等於虛假，引用主張需全文確認；統計檢查無法取代原始資料重算。`;}
$('#ai-provider').addEventListener('change',()=>{$('#ai-key').value='';$('#openalex-key').value='';$('#ai-consent').checked=false;$('#ai-model').value=providerInfo().model;updateProvider();message('已切換供應商並清除金鑰，請輸入對應金鑰並重新確認資料傳送。');});updateProvider();
function styles(){return[...document.querySelectorAll('[name=ai-style]:checked')].map(el=>el.value);}
function tasks(){return[...document.querySelectorAll('[name=ai-task]:checked')].map(el=>el.value);}
function showTab(tab){for(const el of document.querySelectorAll('[data-ai-panel]'))el.hidden=el.dataset.aiPanel!==tab;for(const el of document.querySelectorAll('[data-ai-tab]'))el.setAttribute('aria-pressed',String(el.dataset.aiTab===tab));}
for(const el of document.querySelectorAll('[data-ai-tab]'))el.addEventListener('click',()=>showTab(el.dataset.aiTab));
$('#open-ai').addEventListener('click',()=>{const ctx=getAIContext(),select=$('#ai-ref-start');const previous=select.value;select.replaceChildren(new Option('未辨識／不分析參考文獻區段','-1'));if(ctx.thesis){for(const p of ctx.thesis.info.paragraphs.filter(x=>x.text.trim()))select.add(new Option(`${p.index+1} · ${p.text.slice(0,65)}`,String(p.index)));select.value=selectionDoc===ctx.thesis&&previous&&[...select.options].some(x=>x.value===previous)?previous:String(referenceStart(ctx.thesis.info.paragraphs));}selectionDoc=ctx.thesis;dialog.showModal();estimate();});
$('#ai-close').addEventListener('click',()=>{if(controller){message('分析進行中，請先按「取消分析」。');return;}$('#ai-key').value='';$('#openalex-key').value='';dialog.close();});dialog.addEventListener('cancel',e=>{if(controller){e.preventDefault();message('分析進行中，請先取消分析。');}else $('#ai-key').value='';$('#openalex-key').value='';});
$('#ai-enabled').addEventListener('change',()=>{if(!$('#ai-enabled').checked){$('#ai-key').value='';$('#openalex-key').value='';controller?.abort();}$('#ai-options').disabled=!$('#ai-enabled').checked;});
$('#ai-clear-key').addEventListener('click',()=>{$('#ai-key').value='';$('#openalex-key').value='';message('金鑰已清除。');});
$('#ai-cancel').addEventListener('click',()=>controller?.abort());
document.addEventListener('thesis-context-changed',()=>{controller?.abort();report=null;externalReview=null;snapshot=null;selectionDoc=null;viewPage=0;selectedRules.clear();render();});
function estimate(){const ctx=getAIContext(),selected=tasks();const total=ctx.thesis?.info.paragraphs.reduce((n,p)=>n+p.text.length,0)||0;$('#ai-coverage').textContent=ctx.thesis?`論文 ${ctx.thesis.info.paragraphs.length} 段、約 ${total.toLocaleString()} 字元。${selected.includes('citations')||selected.includes('statistics')?'本文會分批送交 AI 分析。':'只傳送勾選模組需要的規範或書目內容。'} 各模組可分別執行。統計與引用僅查錯，不改寫文字或數值。`:'請先在工作台上傳論文；若要分析規範，也請先載入規範。';}
document.querySelectorAll('[name=ai-task],[name=ai-style],#ai-ref-start').forEach(el=>el.addEventListener('change',estimate));
function safeRules(rules,text){const ranges={top:[0,10],bottom:[0,10],left:[0,10],right:[0,10],size:[6,72],line:[.5,4]},normalize=s=>s.normalize('NFKC').replace(/\s/g,'');const result=[];for(const r of rules){if(!r.evidence||!normalize(text).includes(normalize(r.evidence)))continue;if(r.key in ranges){const v=+r.value,[min,max]=ranges[r.key];if(!Number.isFinite(v)||v<min||v>max)continue;}else if(r.key==='paper'&&!['A4','Letter'].includes(r.value)||r.key==='color'&&r.value!=='黑色'||r.key==='page'&&r.value!=='頁尾置中'||['cjk','latin'].includes(r.key)&&r.value.length>80)continue;if(!['paper','top','bottom','left','right','cjk','latin','size','line','color','page'].includes(r.key))continue;result.push(r);}return result.filter((r,_,all)=>all.filter(x=>x.key===r.key).every(x=>x.value===r.value)).filter((r,i,all)=>all.findIndex(x=>x.key===r.key)===i);}
async function analyze(){if(controller)return;const provider=$('#ai-provider').value;const ctx=getAIContext(),selected=tasks(),selectedStyles=styles(),targetStyle=$('#ai-target-style').value;
  if(!$('#ai-enabled').checked)throw Error('請先勾選 AI 進階分析。');if(!ctx.thesis)throw Error('請先上傳 Word 論文。');if(selected.includes('requirements')&&!ctx.requirements)throw Error('請先載入學校格式規範。');if(!selected.length)throw Error('請至少勾選一個分析模組。');if(selected.includes('references')&&(!selectedStyles.length||!selectedStyles.includes(targetStyle)))throw Error('請勾選要檢查的引用格式，並將主要檢查標準設為其中一種。');let key=$('#ai-key').value.trim();if(!key||/\s/.test(key))throw Error(`請輸入有效的 ${providerInfo().label} API Key。`);if(!$('#ai-consent').checked)throw Error('請閱讀並勾選資料傳送與費用說明。');const model=$('#ai-model').value.trim();if(!/^[a-zA-Z0-9._:-]+$/.test(model))throw Error('模型名稱格式不正確。');
  let openalexKey=$('#openalex-key').value.trim();if(/\s/.test(openalexKey))throw Error('OpenAlex 金鑰不可包含空白。');const sources=[...document.querySelectorAll('[name=database]:checked')].map(el=>el.value);const paragraphs=ctx.thesis.info.paragraphs,refs=referenceRows(paragraphs,Number($('#ai-ref-start').value));if((selected.includes('references')||selected.includes('citations'))&&!refs.length)throw Error('請指定參考文獻標題所在段落，確認其後有文獻內容。');if(refs.length>200)throw Error('目前單次支援最多 200 個書目段落，請使用分章文件分析。');if(paragraphs.reduce((n,p)=>n+p.text.length,0)>300000)throw Error('目前單次支援 30 萬字元，請先將論文分章後分析。');if((ctx.requirements?.text.length||0)>60000&&selected.includes('requirements'))throw Error('格式規範超過 6 萬字元，請擷取論文相關部分再上傳。');
  const body=paragraphs.filter(p=>p.index<=Number($('#ai-ref-start').value)||Number($('#ai-ref-start').value)<0);const jobs=[];
  if(selected.includes('requirements'))jobs.push({tasks:['requirements'],requirements:ctx.requirements.text,notes:'Analyze the school requirements and extract only supported rules. Do not claim actual layout compliance: this task receives requirements, not rendered pages.'});
  if(selected.includes('references'))for(const group of batches(refs.map(r=>({index:r.paragraph-1,text:r.text})),9000))jobs.push({tasks:['references'],paragraphs:group,styles:selectedStyles,targetStyle});
  const bodyTasks=selected.filter(x=>['citations','statistics'].includes(x));if(bodyTasks.length)for(const group of batches(body))jobs.push({tasks:bodyTasks,paragraphs:group,notes:'Only this batch of extracted text is supplied. Equations in images, visual table layout and raw data are not supplied. Check citation correspondence and statistical reporting with these limits.'});
  controller=new AbortController();setAILock(true);$('#ai-options').disabled=true;$('#ai-run').disabled=true;$('#ai-cancel').disabled=false;$('#ai-key').value='';$('#openalex-key').value='';snapshot=ctx;viewPage=0;selectedRules.clear();report={externalReview,name:ctx.thesis.name,date:new Date().toLocaleString('zh-TW'),provider:PROVIDERS[provider].label,model,targetStyle,styles:selectedStyles,tasks:selected,status:'分析中',findings:[],rules:[],registry:[],summaries:[],coverage:[`抽取 ${paragraphs.length} 個段落；書目區段 ${refs.length} 個非空段落。書目以每段為一筆查詢，跨段文獻需人工合併確認。`,`預計 ${jobs.length} 個 AI 批次。圖片內文字與公式圖像不在分析範圍。`],completed:0,planned:jobs.length,inputTokens:0,outputTokens:0};render();
  try{
    if(selected.includes('statistics')){const stats=checkStatistics(body);report.findings.push(...stats.findings);report.coverage.push(`統計規則掃描 ${body.length} 段；可依文字重算 ${stats.recomputed} 組檢定 p 值（t 採雙尾、F／卡方採上尾）。`);}
    if(selected.includes('references')||selected.includes('citations')){for(let i=0;i<refs.length;i++){controller.signal.throwIfAborted();message(`文獻資料查詢 ${i+1} / ${refs.length}…`);report.registry.push(await verifySources(refs[i],controller.signal,{sources,openalexKey}));render();}report.coverage.push('自動查詢來源：'+(sources.map(id=>DATABASES[id].name).join('、')||'未選取')+'；華藝、博碩士論文網、Web of Science、Scopus、Google Scholar 為人工查證入口，未自動查詢。');report.coverage.push(`已產生 ${report.registry.length}/${refs.length} 筆書目查詢紀錄；實際成功或失敗見各筆狀態。`);}
    for(let i=0;i<jobs.length;i++){controller.signal.throwIfAborted();const job=jobs[i];message(`AI 分析 ${i+1} / ${jobs.length}：${job.tasks.map(x=>LABELS[x]).join('、')}…`);const ids=new Set(job.paragraphs?.map(p=>p.paragraph));const registry=job.tasks.includes('requirements')?[]:report.registry.filter(r=>job.tasks.includes('references')?ids.has(r.paragraph):true).map(r=>({paragraph:r.paragraph,original:r.text,status:r.status,sources:r.checks.map(c=>({database:c.database,mode:c.mode,status:c.status,checkedAt:c.checkedAt,source:c.source})),candidates:r.checks.flatMap(c=>c.candidates.slice(0,1).map(item=>({...item,database:c.database}))).map(c=>({...c,abstract:job.tasks.includes('citations')?c.abstract.slice(0,2500):''}))}));
      const result=await requestAnalysis({provider,key,model,signal:controller.signal,payload:{...job,registry,totalBatches:jobs.length,batchNumber:i+1}});report.completed++;report.inputTokens+=result.usage.input_tokens||0;report.outputTokens+=result.usage.output_tokens||0;report.summaries.push(result.summary);report.findings.push(...result.findings.filter(f=>job.tasks.includes(f.category)).map(f=>({...f,origin:'AI 判讀，須人工審閱'})));if(job.tasks.includes('requirements'))report.rules=safeRules(result.rules,ctx.requirements.text);
      report.coverage.push(`完成批次 ${i+1}：${job.tasks.map(x=>LABELS[x]).join('、')}${job.paragraphs?`，第 ${job.paragraphs[0].paragraph}–${job.paragraphs.at(-1).paragraph} 段`:''}。`);render();
    }report.status=report.registry.some(r=>r.checks.some(c=>c.outcome==='error'))?'AI 批次已完成，部分外部查證失敗':'所選 AI 批次已完成（仍有待確認項目）';message('分析完成。請查看檢核結果與格式建議，並下載報告。');showTab('findings');
  }catch(e){report.status=e.name==='AbortError'?'已取消，這是部分結果':'未全部完成，這是部分結果';report.coverage.push('未完成原因：'+(e.name==='AbortError'?'使用者取消':e.message));message(report.status+'：'+(e.name==='AbortError'?'可下載已完成部分的報告。':e.message),true);showTab('findings');}finally{key='';openalexKey='';controller=null;setAILock(false);$('#ai-options').disabled=!$('#ai-enabled').checked;$('#ai-run').disabled=false;$('#ai-cancel').disabled=true;render();}
}
$('#ai-run').addEventListener('click',()=>analyze().catch(e=>message(e.message,true)));
function pageItems(){if(!report)return[];const category=$('#ai-filter').value;return report.findings.filter(f=>category==='all'||f.category===category);}
function render(){renderRegistry();for(const el of document.querySelectorAll('[name=database],#openalex-key'))el.disabled=!!controller;const available=!!report&&!controller;for(const id of ['#ai-html','#ai-pdf'])$(id).disabled=!available;$('#ai-report-state').textContent=report?`${report.status} · 完成 ${report.completed}/${report.planned} 批 · ${report.findings.length} 項發現 · ${report.registry.length} 筆查證`:'尚未分析';const items=pageItems(),pages=Math.max(1,items.length);viewPage=Math.min(viewPage,pages-1);$('#ai-findings').replaceChildren();for(const f of items.slice(viewPage,viewPage+1)){const card=document.createElement('li');const title=document.createElement('strong');title.textContent=`${viewPage+1}. ${LABELS[f.category]} · ${f.severity==='problem'?'需修正':f.severity==='review'?'待確認':'資訊'} · ${f.location}`;card.dataset.severity=f.severity;card.append(title);for(const [label,text]of [['證據',f.evidence],['判讀',f.explanation],['建議',f.suggestion]]){const p=document.createElement('p');p.textContent=label+'：'+text;card.append(p);}$('#ai-findings').append(card);}if(!items.length)$('#ai-findings').textContent=report?'目前沒有此類檢核發現；請查看報告的完成度。':'啟用 AI 並選擇模組後，開始分析。';$('#ai-page').textContent=`${viewPage+1} / ${pages} 頁`;$('#ai-prev').disabled=viewPage===0;$('#ai-next').disabled=viewPage===pages-1;
  $('#ai-rule-list').replaceChildren();for(const [i,r]of (report?.rules||[]).entries()){const label=document.createElement('label');label.className='ai-rule';const input=document.createElement('input');input.type='checkbox';input.checked=selectedRules.has(i);input.disabled=!!controller;input.addEventListener('change',()=>{input.checked?selectedRules.add(i):selectedRules.delete(i);$('#ai-use-rules').disabled=!selectedRules.size||!!controller;});label.append(input,document.createTextNode(` ${RULE_LABELS[r.key]||r.key}：${r.value}；依據：${r.evidence}`));$('#ai-rule-list').append(label);}$('#ai-use-rules').disabled=!selectedRules.size||!!controller;
}
$('#ai-filter').addEventListener('change',()=>{viewPage=0;render();});$('#ai-prev').addEventListener('click',()=>{viewPage--;render();});$('#ai-next').addEventListener('click',()=>{viewPage++;render();});
$('#ai-html').addEventListener('click',()=>{if(report)download(new Blob([reportHTML(report)],{type:'text/html;charset=utf-8'}),'論文AI檢查報告.html');});
$('#ai-pdf').addEventListener('click',async()=>{if(!report)return;$('#ai-pdf').disabled=true;try{download(await exportPDF(reportHTML(report),text=>message(text)),'論文AI檢查報告.pdf');message('PDF 報告已下載。另提供可搜尋、可列印的 HTML 版本。');}catch(e){message(e.message,true);}finally{$('#ai-pdf').disabled=false;}});
$('#ai-use-rules').addEventListener('click',()=>{if(!report||!snapshot)return;applyAIRules([...selectedRules].map(i=>report.rules[i]));message('已將勾選的格式建議填入工作台。仍需在工作台預覽並確認套用。');});

function currentCheck(){return report?.registry[Number($('#registry-reference').value)]?.checks[Number($('#registry-source').value)];}
function renderRegistry(){const refSelect=$('#registry-reference'),dbSelect=$('#registry-source'),ri=refSelect.value||'0',si=dbSelect.value||'0';refSelect.replaceChildren(...(report?.registry||[]).map((r,i)=>new Option(`第 ${r.paragraph} 段 · ${r.text.slice(0,70)}`,String(i))));refSelect.value=[...refSelect.options].some(o=>o.value===ri)?ri:'0';const row=report?.registry[Number(refSelect.value)];dbSelect.replaceChildren(...(row?.checks||[]).map((c,i)=>new Option(c.database+(c.manual?' · 已登錄人工結果':''),String(i))));dbSelect.value=[...dbSelect.options].some(o=>o.value===si)?si:'0';const check=currentCheck(),box=$('#registry-detail');box.replaceChildren();$('#manual-check').hidden=!check||check.mode!=='manual';$('#save-manual').disabled=!!controller;if(!check){box.textContent='先選取文獻或引用模組並開始分析，即可逐筆查看來源與登錄人工結果。';return;}const p=document.createElement('p');p.textContent=check.manual?'已登錄人工查證（系統未獨立驗證）':check.status;box.append(p);const query=document.createElement('p');query.textContent='查詢文字／DOI：'+(check.query||row.text);box.append(query);const link=document.createElement('a');link.href=DATABASES[check.id].mode==='manual'?check.source:DATABASES[check.id].home;link.target='_blank';link.rel='noopener noreferrer';link.textContent='開啟 '+check.database+' 官方查證網站 ↗';box.append(link);const copy=document.createElement('button');copy.className='subtle';copy.textContent='複製查詢文字';copy.addEventListener('click',()=>navigator.clipboard.writeText(check.query||row.text).then(()=>message('查詢文字已複製，請在資料庫貼上搜尋。')).catch(()=>message('無法複製，請選取上方文字手動複製。',true)));box.append(copy);for(const c of check.candidates){const item=document.createElement('p');item.textContent=`候選：${c.title}（${c.year??'年份未提供'}）｜${c.doi||c.recordId||'無 DOI'}；完整作者與出版資訊見報告。`;box.append(item);}if(check.manual){const item=document.createElement('p');item.className='manual-result';item.textContent=check.manual.label+'｜'+check.manual.note;box.append(item);}$('#manual-url').value=check.manual?.url||'';$('#manual-note').value=check.manual?.note||'';$('#manual-status').value=check.manual?.status||'matched';}
$('#registry-reference').addEventListener('change',()=>{$('#registry-source').value='0';renderRegistry();});$('#registry-source').addEventListener('change',renderRegistry);
$('#save-manual').addEventListener('click',()=>{if(controller)return;try{const check=currentCheck();if(!check||check.mode!=='manual')return;saveManualCheck(check,{url:$('#manual-url').value.trim(),status:$('#manual-status').value,note:$('#manual-note').value});renderRegistry();message('已登錄人工查證結果。重新下載 HTML／PDF 報告即可包含此紀錄；論文未變更。');}catch(e){message(e.message,true);}});
document.querySelectorAll('[name=database],#openalex-key').forEach(el=>el.addEventListener('change',()=>{$('#ai-consent').checked=false;}));
window.addEventListener('pagehide',()=>{$('#ai-key').value='';$('#openalex-key').value='';controller?.abort();});render();

document.addEventListener('refcheck-imported',e=>{externalReview=e.detail;if(report)report.externalReview=externalReview;});
