import {AUTHOR,DISCLAIMER} from './notice.js?v=20260921-direct8';
import {refreshChecklist} from './checklist.js';
import {readRequirement, openDocx, inspectDocx, formatDocx} from './engine.js';
const $=s=>document.querySelector(s);
const defs=[['paper','紙張大小','select',['A4','Letter']],['top','上邊界（公分）','number'],['bottom','下邊界（公分）','number'],['left','左邊界（公分）','number'],['right','右邊界（公分）','number'],['cjk','中文字型','text'],['latin','英文字型','text'],['size','本文字級（pt）','number'],['line','本文行距（倍）','number'],['color','本文文字顏色','select',['黑色']],['page','頁碼位置','select',['頁尾置中']]];
let thesis=null,requirements=null,rules={},output=null,report='',busy=false,plan=null;
const LIBRARY_KEY='thesis-studio-requirements-v1';
let library=[];
try{const saved=JSON.parse(localStorage.getItem(LIBRARY_KEY)||'[]');if(Array.isArray(saved))library=saved.filter(x=>x&&typeof x.id==='string'&&typeof x.name==='string'&&typeof x.text==='string'&&x.text.length<=1500000&&typeof x.date==='string');}catch{}
function drawLibrary(selected=''){const select=$('#saved-requirements');while(select.options.length>2)select.remove(2);for(const item of library)select.add(new Option(`${item.name}｜${item.date}`,item.id));select.value=selected;}
async function rememberRequirement(text,name){const normalized=text.normalize('NFKC').replace(/\s+/g,' ').trim();const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(normalized));const id=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');const exists=library.find(x=>x.id===id);if(!exists)library.unshift({id,name,text,date:new Date().toLocaleDateString('zh-TW')});drawLibrary(id);try{localStorage.setItem(LIBRARY_KEY,JSON.stringify(library));$('#library-note').textContent='規範已記住，下次可從下拉選單選取。僅儲存於目前瀏覽器，不保存論文；不跨裝置同步。';}catch{$('#library-note').textContent='瀏覽器儲存空間不足或禁止儲存：本次仍可使用規範，但關閉後可能需重新上傳。';}}
const status=(text,error=false)=>{$('#status').textContent=text;$('#status').classList.toggle('error',error);};
function invalidate(){plan=null;$('#plan').hidden=true;output=null;report='';$('#result').hidden=true;update();}
function update(){$('#review-empty').hidden=!!plan||!!output;$('#confirm-format').disabled=busy||!plan;const enabled=Object.values(rules).filter(r=>r.enabled).length;$('#format').disabled=busy||!thesis||!requirements||!enabled;$('#ready-text').textContent=busy?'處理中，請稍候…':thesis&&requirements?`將套用 ${enabled} 項排版設定`:'完成匯入後即可整理';$('#rule-count').textContent=requirements?`${enabled} 項已選取`:'等待讀取';$('#top-preview').textContent=rules.top?.enabled?`上邊界 ${rules.top.value} cm`:'上邊界 —';$('#preview-values').textContent=defs.filter(([key])=>rules[key]?.enabled).map(([key,label])=>`${label}：${rules[key].value}`).join(' · ')||'載入規範後，這裡會顯示排版設定。';$('.steps li:nth-child(2)').classList.toggle('active',!!requirements);$('.steps li:nth-child(3)').classList.toggle('active',!!output);updateGuidance();}
function updateGuidance(){const stage=output||plan?3:thesis&&requirements?2:1;for(const item of document.querySelectorAll('.steps [data-stage]')){const n=Number(item.dataset.stage),done=n<stage||(n===3&&!!output);item.classList.toggle('active',n===stage);item.classList.toggle('complete',done);if(n===stage)item.setAttribute('aria-current','step');else item.removeAttribute('aria-current');item.querySelector('.stage-state').textContent=done?'已完成':n===stage?'目前步驟':'待操作';}$('#guide-import').textContent=thesis&&requirements?'論文與規範已就緒，可繼續設定':thesis?'下一步：上傳或選取學校規範':requirements?'下一步：上傳 Word 論文':'上傳 Word，再上傳或選取學校規範';$('#guide-format').textContent=stage===2?'下一步：核對設定及正文起點，點選預覽':'核對設定與正文起點，再列出修改項目';$('#guide-download').textContent=output?'已完成：下載 Word 及修改說明':plan?'下一步：查看各類清單，確認後產生 Word':'逐項檢視 → 確認套用 → 下載 Word';}
$('#guide-ai').addEventListener('click',()=>$('#open-ai').click());
function drawRules(){const container=$('#rules');container.replaceChildren();for(const [key,label,type,options] of defs){const rule=rules[key]??={value:'',enabled:false,evidence:''};const box=document.createElement('div');box.className='rule';const lab=document.createElement('label');lab.className='rule-label';const check=document.createElement('input');check.type='checkbox';check.checked=rule.enabled;check.id=`enable-${key}`;lab.append(check,document.createTextNode(label));const input=document.createElement(type==='select'?'select':'input');input.id=`rule-${key}`;input.setAttribute('aria-label',label);if(type==='select'){input.add(new Option('保留原格式',''));for(const v of options)input.add(new Option(v,v));}else{input.type=type;if(type==='number'){input.min=key==='size'?'6':key==='line'?'0.5':'0';input.max=key==='size'?'72':key==='line'?'4':'10';input.step='0.1';}input.placeholder='未辨識，保留原格式';}input.value=rule.value;const evidence=document.createElement('small');evidence.textContent=rule.evidence||'原文未明確辨識；如要套用，可自行指定。';check.addEventListener('change',()=>{rule.enabled=check.checked;invalidate();});input.addEventListener('input',()=>{rule.value=input.value;rule.enabled=!!input.value;check.checked=rule.enabled;rule.evidence='使用者手動指定';evidence.textContent=rule.evidence;invalidate();});const sourceDetails=document.createElement('details');sourceDetails.className='rule-evidence';const sourceSummary=document.createElement('summary');sourceSummary.textContent='來源';sourceDetails.append(sourceSummary,evidence);box.append(lab,input,sourceDetails);container.append(box);}update();}
async function loadRules(text,name){document.dispatchEvent(new Event('thesis-context-changed')); rules=readRequirement(text);requirements={name,text};$('#source').textContent=text;$('#requirements-name').textContent=name;invalidate();drawRules();status(`已讀取「${name}」。請檢視擷取結果；未辨識與特殊要求請參閱原文。`);}
function lock(value){busy=value;for(const s of ['#thesis','#requirements','#preset','#saved-requirements','#scope','#body-start'])$(s).disabled=value||(s==='#body-start'&&!thesis);for(const el of document.querySelectorAll('#rules input,#rules select'))el.disabled=value;update();}
async function upload(file,kind){if(!file||busy)return;document.dispatchEvent(new Event('thesis-context-changed'));lock(true);invalidate();status('正在讀取檔案…');try{if(file.size>(kind==='thesis'?30:15)*1024*1024)throw Error('檔案超過大小上限，請縮小後再試。');const ext=file.name.split('.').pop().toLowerCase();if(kind==='thesis'){if(ext!=='docx')throw Error('論文請使用 .docx。舊版 .doc 請先在 Word 另存為 .docx。');const bytes=await file.arrayBuffer();const zip=await openDocx(bytes);const info=await inspectDocx(zip);thesis={name:file.name,bytes,info};$('#thesis-name').textContent=file.name;const start=$('#body-start');start.replaceChildren();start.add(new Option('請選擇正文起點',''));for(const p of info.paragraphs.filter(p=>p.text.trim()))start.add(new Option(`${p.index+1} · ${p.text.slice(0,80)}`,String(p.index)));if(info.start>=0)start.value=String(info.start);status(`已讀取 ${info.paragraphs.filter(p=>p.text.trim()).length} 個段落。${info.start>=0?'已找到可能的正文起點，請確認。':'請選擇正文起始段落，或改為套用全文一般段落。'}`);}else{let text='';if(ext==='txt')text=await file.text();else if(ext==='docx'){const zip=await openDocx(await file.arrayBuffer());text=(await inspectDocx(zip)).paragraphs.map(p=>p.text).join('\n');}else if(ext==='pdf'){const pdfjs=await import('./vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;try{if(pdf.numPages>150)throw Error('規範 PDF 超過 150 頁，請擷取相關章節再上傳。');for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n);const content=await page.getTextContent();text+=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('')+'\n';}}finally{await pdf.destroy();}}else throw Error('規範請使用 PDF、.docx 或 UTF-8 TXT。');if(text.replace(/\s/g,'').length<30)throw Error('無法讀取足夠文字。掃描 PDF 請先做文字辨識（OCR），或改用文字版規範。');await loadRules(text,file.name);await rememberRequirement(text,file.name);}}catch(e){if(kind==='thesis'){thesis=null;$('#thesis-name').textContent='讀取失敗，請重新選擇';$('#body-start').replaceChildren(new Option('上傳論文後選擇',''));}else{requirements=null;rules={};$('#requirements-name').textContent='讀取失敗，請重新選擇';$('#source').textContent='尚未載入格式要求。';drawRules();}status(e.message||'無法讀取檔案，請確認格式及密碼保護。',true);}finally{lock(false);}}
for(const kind of ['thesis','requirements']){const input=$(`#${kind}`),drop=$(`#${kind}-drop`);input.addEventListener('change',()=>upload(input.files[0],kind));drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag');});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');upload(e.dataTransfer.files[0],kind);});}
async function loadPreset(){if(busy)return;lock(true);try{const response=await fetch('./nthu.json');if(!response.ok)throw Error('無法載入清大規範');await loadRules((await response.json()).text,'清大研究生畢業論文格式｜114.05.29');$('#saved-requirements').value='nthu';}catch(e){status(e.message,true);}finally{lock(false);}}
$('#preset').addEventListener('click',loadPreset);
$('#saved-requirements').addEventListener('change',async()=>{if(busy)return;const id=$('#saved-requirements').value;if(id==='nthu')return loadPreset();const saved=library.find(x=>x.id===id);if(saved){await loadRules(saved.text,saved.name);}else{document.dispatchEvent(new Event('thesis-context-changed'));requirements=null;rules={};$('#source').textContent='尚未載入格式要求。';$('#requirements-name').textContent='尚未選擇檔案';invalidate();drawRules();}});
$('#scope').addEventListener('change',invalidate);$('#body-start').addEventListener('change',invalidate);
async function run(mode='preview'){if(mode==='apply'&&!plan)throw Error('請先重新檢視預計修改清單。');if(busy||!thesis||!requirements)throw Error('請先上傳論文及讀取格式要求。');const selected={};for(const [key,label,type] of defs){const r=rules[key];if(!r?.enabled)continue;if(!String(r.value).trim())throw Error(`請填寫「${label}」，或取消勾選。`);if(type==='number'){const n=Number(r.value),el=$(`#rule-${key}`);if(!Number.isFinite(n)||n<Number(el.min)||n>Number(el.max))throw Error(`「${label}」超出可用範圍（${el.min}–${el.max}）。`);selected[key]=n;}else selected[key]=r.value;}if(!Object.keys(selected).length)throw Error('請至少選擇一項排版設定。');const start=$('#scope').value==='all'?0:Number($('#body-start').value);if($('#scope').value==='body'&&$('#body-start').value==='')throw Error('請先選擇正文起始段落。');lock(true);invalidate();status(mode==='preview'?'正在比對論文與格式要求，整理預計修改清單…':'正在套用已確認的修改…');await new Promise(resolve=>setTimeout(resolve,30));try{const result=await formatDocx(thesis.bytes,selected,start,{preview:mode==='preview'});const changes=result.changes;const warnings=[...result.warnings];warnings.push('請在 Word 中更新目錄、圖表目錄與頁碼，並檢查實際分頁；此工具不執行 Word 的分頁引擎。','封面、書名頁、簽章文件、章節順序、摘要頁數與關鍵詞、圖表標號及引用格式需人工核對；本工具不代寫或移動內容。');if(/清華/.test(requirements.text))warnings.push('清大規範另要求封面中英並列、封面後一頁空白頁、摘要關鍵詞 5–7 個、圖說在下／表說在上；請對照原文逐項確認。','紙本封底、書背、米黃色封面、裝訂與繳交份數需於印製時處理。');if(mode==='preview'){plan={changes,warnings};for(const [selector,items]of [['#planned-changes',changes.length?changes:['選取的設定與原檔一致，無新增修改。']],['#planned-locations',result.locations.length?result.locations:['沒有段落或頁面格式需要修改；欄位更新設定如有變動會列於上方。']],['#planned-warnings',warnings]]){$(selector).replaceChildren(...items.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));}$('#plan-summary').textContent=`「${thesis.name}」將依「${requirements.name}」調整。請先檢視以下項目，確認後才產生修改檔。`;$('#plan').hidden=false;refreshChecklist('plan');status('已列出預計修改的位置及範圍，尚未套用。');if(innerWidth<1000)$('#plan').scrollIntoView({behavior:'smooth',block:'start'});return{changes,warnings};}output=result.blob;report=`論文格式修改說明\n網站作者：${AUTHOR}\n免責聲明：${DISCLAIMER}\n\n論文：${thesis.name}\n格式來源：${requirements.name}\n時間：${new Date().toLocaleString('zh-TW')}\n文字範圍：第 ${start+1} 個段落起（排除表格、標題、公式及圖說）\n\n已修改\n${changes.map(s=>'• '+s).join('\n')||'• 選取的設定與原檔一致，無新增修改。'}\n\n仍需確認\n${warnings.map(s=>'• '+s).join('\n')}\n\n套用設定與來源\n${defs.filter(([key])=>rules[key]?.enabled).map(([key,label])=>`• ${label}：${rules[key].value}；${rules[key].evidence}`).join('\n')}`;for(const [selector,items]of [['#changes',changes.length?changes:['選取的設定與原檔一致，無新增修改。']],['#warnings',warnings]]){$(selector).replaceChildren(...items.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));}$('#result-summary').textContent=`已產生 ${thesis.name.replace(/\.docx$/i,'')}_格式修改.docx。原文、圖片及公式資料均已保留；以下紀錄依實際修改產生。`;$('#result').hidden=false;refreshChecklist('result');status('排版檔與修改說明已準備好，可分別下載。');if(innerWidth<1000)$('#result').scrollIntoView({behavior:'smooth',block:'start'});return{changes,warnings};}finally{lock(false);}}
$('#format').addEventListener('click',()=>run('preview').catch(e=>status(e.message,true)));
$('#confirm-format').addEventListener('click',()=>run('apply').catch(e=>status(e.message,true)));
$('#back-to-rules').addEventListener('click',()=>{invalidate();$('#rules-panel').scrollIntoView({behavior:'smooth'});status('調整設定後，請重新列出預計修改項目。');});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('#download').addEventListener('click',()=>{if(output)download(output,thesis.name.replace(/\.docx$/i,'')+'_格式修改.docx');});$('#report').addEventListener('click',()=>{if(report)download(new Blob(['\ufeff'+report],{type:'text/plain;charset=utf-8'}),thesis.name.replace(/\.docx$/i,'')+'_修改說明.txt');});
drawLibrary();drawRules();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_thesis_format_status',description:'讀取目前論文、規範與選取的排版設定；不讀取論文全文。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw Error('不接受參數');return{thesis:thesis?.name??null,requirements:requirements?.name??null,settings:Object.fromEntries(Object.entries(rules).filter(([,r])=>r.enabled).map(([k,r])=>[k,r.value])),downloadReady:!!output};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

export function getAIContext(){return{thesis,requirements,formatted:output};}
export function setAILock(value){lock(value);}
export function applyAIRules(proposals){for(const r of proposals)rules[r.key]={value:r.value,enabled:true,evidence:'AI 擷取；原文：'+r.evidence};invalidate();drawRules();}
