import {getAIContext,setAILock} from './app.js?v=20260921-gemini3';
import {DATABASES,verifySources,saveManualCheck} from './sources.js?v=20260921-gemini3';
import {referenceStart,referenceRows,checkStatistics} from './ai-core.js?v=20260921-gemini3';
import {assessReference} from './reference-assessment.js?v=20260921-gemini3';
import {reportHTML,exportPDF,escapeHTML as e} from './ai-report.js?v=20260921-gemini3';
const $=s=>document.querySelector(s),dialog=$('#basic-dialog');let report=null,controller=null,page=0,statPage=0,selectionDoc=null;
export function getBasicReport(){return report;}
function message(t,error=false){$('#basic-status').textContent=t;$('#basic-status').classList.toggle('error',error);}
function showTab(tab){document.querySelectorAll('[data-basic-panel]').forEach(x=>x.hidden=x.dataset.basicPanel!==tab);document.querySelectorAll('[data-basic-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.basicTab===tab)));}
document.querySelectorAll('[data-basic-tab]').forEach(x=>x.onclick=()=>showTab(x.dataset.basicTab));
$('#open-basic').onclick=()=>{const ctx=getAIContext(),select=$('#basic-start');if(selectionDoc!==ctx.thesis){select.replaceChildren(new Option('未辨識參考文獻標題','-1'));for(const p of ctx.thesis?.info.paragraphs||[])if(p.text.trim())select.add(new Option(`${p.index+1} · ${p.text.slice(0,65)}`,String(p.index)));select.value=String(referenceStart(ctx.thesis?.info.paragraphs||[]));selectionDoc=ctx.thesis;}dialog.showModal();};
$('#basic-close').onclick=()=>{if(controller){message('請先取消正在執行的檢查。');return;}$('#openalex-key').value='';dialog.close();};
dialog.oncancel=event=>{if(controller)event.preventDefault();else $('#openalex-key').value='';};
$('#basic-cancel').onclick=()=>controller?.abort();
document.addEventListener('thesis-context-changed',()=>{controller?.abort();report=null;selectionDoc=null;page=0;statPage=0;render();});
document.querySelectorAll('[name=database]').forEach(x=>x.onchange=()=>{$('#basic-consent').checked=false;});
async function run(){if(controller)return;const ctx=getAIContext();if(!ctx.thesis)throw Error('請先上傳 Word 論文。');const useRefs=$('#basic-refs').checked,useStats=$('#basic-stats').checked;if(!useRefs&&!useStats)throw Error('請至少勾選一項基本檢查。');if(useRefs&&!$('#basic-consent').checked)throw Error('請先確認資料庫查詢的資料傳送說明。');const sources=[...document.querySelectorAll('[name=database]:checked')].map(x=>x.value);if(useRefs&&!sources.length)throw Error('請在資料來源至少選一個自動查詢來源。');const paragraphs=ctx.thesis.info.paragraphs,start=Number($('#basic-start').value),refs=useRefs?referenceRows(paragraphs,start):[];if(useRefs&&!refs.length)throw Error('請確認參考文獻標題所在段落。');if(refs.length>200)throw Error('單次最多 200 個書目段落，請分章檢查。');let key=$('#openalex-key').value.trim();if(/\s/.test(key))throw Error('OpenAlex 金鑰不可包含空白。');$('#openalex-key').value='';controller=new AbortController();setAILock(true);page=0;statPage=0;
 const active={name:ctx.thesis.name,date:new Date().toLocaleString('zh-TW'),provider:'基本檢查（無 AI）',model:'規則與學術資料庫',tasks:[],styles:[],targetStyle:'未檢查引用樣式',status:'檢查中',findings:[],rules:[],registry:refs.map(r=>({...r,checks:sources.map(id=>({id,database:DATABASES[id].name,mode:'api',outcome:'pending',status:'尚未查詢',candidates:[]}))})),summaries:[],coverage:['每個非空書目段落視為一筆；跨段文獻需人工確認。','統計僅查錯，不修改數值；書目基本比對不代表引用主張正確。'],completed:0,planned:0,inputTokens:0,outputTokens:0};report=active;render();
 try{if(useStats){const body=paragraphs.filter(p=>start<0||p.index<start),stats=checkStatistics(body);active.findings.push(...stats.findings);active.coverage.push(`統計規則掃描 ${body.length} 段；比較 ${stats.recomputed} 組檢定 p 值。t 採雙尾、F／卡方採上尾；未檢查圖片內數據或原始研究資料。`);}if(useRefs){showTab('results');for(let i=0;i<refs.length;i++){controller.signal.throwIfAborted();message(`正在查證第 ${i+1} / ${refs.length} 篇…`);active.registry[i]=await verifySources(refs[i],controller.signal,{sources,openalexKey:key});render();}active.coverage.push('自動查詢：'+sources.map(id=>DATABASES[id].name).join('、')+'。未操作的人工來源不列為已查證。');}else showTab('stats');active.status=active.registry.some(r=>r.checks.some(c=>c.outcome==='error'))?'已檢查；部分來源查詢未完成':'基本檢查完成';message(active.status+'。請逐篇核對結果，再下載報告。');}
 catch(err){active.status=err.name==='AbortError'?'已取消（部分結果）':'檢查中斷（部分結果）';message(active.status+'：'+err.message,true);}finally{key='';controller=null;setAILock(false);render();}}
$('#basic-run').onclick=()=>run().catch(err=>message(err.message,true));
function render(){const busy=!!controller;for(const id of ['basic-run','basic-refs','basic-stats','basic-start','basic-consent','openalex-key'])$('#'+id).disabled=busy;document.querySelectorAll('[name=database]').forEach(x=>x.disabled=busy);$('#basic-cancel').disabled=!busy;$('#basic-html').disabled=$('#basic-pdf').disabled=!report||busy;
 const all=(report?.registry||[]).map((row,i)=>({row,i,a:assessReference(row)})),filter=$('#basic-filter').value,items=all.filter(x=>filter==='all'||x.a.code===filter);page=Math.max(0,Math.min(page,Math.ceil(items.length/2)-1));$('#basic-summary').textContent=all.length?`${all.length} 篇｜OK ${all.filter(x=>x.a.code==='ok').length} · 有疑點 ${all.filter(x=>x.a.code==='problem').length} · 其餘待核對 ${all.filter(x=>!['ok','problem'].includes(x.a.code)).length}`:'尚未產生文獻查證結果';
 $('#basic-results').innerHTML=items.slice(page*2,page*2+2).map(({row,i,a})=>`<article class="basic-reference ${a.code}"><div><strong>R${String(i+1).padStart(3,'0')} · 第 ${row.paragraph} 段</strong><b class="verdict">${e(a.label)}</b></div><p class="reference-original">${e(row.text)}</p><p><strong>${e(a.reasons.join(' '))}</strong></p><small>${e(a.source||'尚無比對證據')}${a.incomplete.length?' · 未完成：'+e(a.incomplete.join('、')):''}</small><button class="subtle" data-reference="${i}">檢視來源／人工查證 ↗</button></article>`).join('')||'<p>沒有符合篩選條件的文獻。</p>';
 $('#basic-results').querySelectorAll('[data-reference]').forEach(x=>x.onclick=()=>{$('#registry-reference').value=x.dataset.reference;renderRegistry();showTab('registry');});$('#basic-page').textContent=`${page+1} / ${Math.max(1,Math.ceil(items.length/2))} 頁`;$('#basic-prev').disabled=page===0;$('#basic-next').disabled=(page+1)*2>=items.length;
 const findings=report?.findings||[];statPage=Math.max(0,Math.min(statPage,findings.length-1));const f=findings[statPage];$('#basic-stat-result').innerHTML=f?`<article class="basic-reference problem"><strong>${e(f.location)}</strong><p><b>${e(f.evidence)}</b></p><p>${e(f.explanation)}</p><p>${e(f.suggestion)}</p><small>${e(f.origin)}</small></article>`:'尚無統計規則發現；請確認是否已執行統計檢查。';$('#basic-stat-page').textContent=`${statPage+1} / ${Math.max(1,findings.length)} 項`;$('#basic-stat-prev').disabled=statPage===0;$('#basic-stat-next').disabled=statPage+1>=findings.length;renderRegistry();}
$('#basic-filter').onchange=()=>{page=0;render();};$('#basic-prev').onclick=()=>{page--;render();};$('#basic-next').onclick=()=>{page++;render();};$('#basic-stat-prev').onclick=()=>{statPage--;render();};$('#basic-stat-next').onclick=()=>{statPage++;render();};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('#basic-html').onclick=()=>{if(report)download(new Blob([reportHTML(report)],{type:'text/html;charset=utf-8'}),'論文基本檢查報告.html');};
$('#basic-pdf').onclick=async()=>{if(!report)return;$('#basic-pdf').disabled=true;try{download(await exportPDF(reportHTML(report),message),'論文基本檢查報告.pdf');message('PDF 已下載。');}catch(err){message(err.message,true);}finally{render();}};
window.addEventListener('pagehide',()=>{controller?.abort();$('#openalex-key').value='';});

function currentCheck(){return report?.registry[Number($('#registry-reference').value)]?.checks[Number($('#registry-source').value)];}
function renderRegistry(){const refSelect=$('#registry-reference'),dbSelect=$('#registry-source'),ri=refSelect.value||'0',si=dbSelect.value||'0';refSelect.replaceChildren(...(report?.registry||[]).map((r,i)=>new Option(`第 ${r.paragraph} 段 · ${r.text.slice(0,70)}`,String(i))));refSelect.value=[...refSelect.options].some(o=>o.value===ri)?ri:'0';const row=report?.registry[Number(refSelect.value)];dbSelect.replaceChildren(...(row?.checks||[]).map((c,i)=>new Option(c.database+(c.manual?' · 已登錄人工結果':''),String(i))));dbSelect.value=[...dbSelect.options].some(o=>o.value===si)?si:'0';const check=currentCheck(),box=$('#registry-detail');box.replaceChildren();$('#manual-check').hidden=!check||check.mode!=='manual';$('#save-manual').disabled=!!controller;if(!check){box.textContent='先在基本檢查選取文獻查證並開始檢查，即可逐筆查看來源與登錄人工結果。';return;}const p=document.createElement('p');p.textContent=check.manual?'已登錄人工查證（系統未獨立驗證）':check.status;box.append(p);const query=document.createElement('p');query.textContent='查詢文字／DOI：'+(check.query||row.text);box.append(query);const link=document.createElement('a');link.href=DATABASES[check.id].mode==='manual'?check.source:DATABASES[check.id].home;link.target='_blank';link.rel='noopener noreferrer';link.textContent='開啟 '+check.database+' 官方查證網站 ↗';box.append(link);const copy=document.createElement('button');copy.className='subtle';copy.textContent='複製查詢文字';copy.addEventListener('click',()=>navigator.clipboard.writeText(check.query||row.text).then(()=>message('查詢文字已複製，請在資料庫貼上搜尋。')).catch(()=>message('無法複製，請選取上方文字手動複製。',true)));box.append(copy);for(const c of check.candidates){const item=document.createElement('p');item.textContent=`候選：${c.title}（${c.year??'年份未提供'}）｜${c.doi||c.recordId||'無 DOI'}；完整書目請開啟來源紀錄核對。`;box.append(item);}if(check.manual){const item=document.createElement('p');item.className='manual-result';item.textContent=check.manual.label+'｜'+check.manual.note;box.append(item);}$('#manual-url').value=check.manual?.url||'';$('#manual-note').value=check.manual?.note||'';$('#manual-status').value=check.manual?.status||'matched';}
$('#registry-reference').addEventListener('change',()=>{$('#registry-source').value='0';renderRegistry();});$('#registry-source').addEventListener('change',renderRegistry);
$('#save-manual').addEventListener('click',()=>{if(controller)return;try{const check=currentCheck();if(!check||check.mode!=='manual')return;saveManualCheck(check,{url:$('#manual-url').value.trim(),status:$('#manual-status').value,note:$('#manual-note').value});render();message('已登錄人工查證結果。重新下載 HTML／PDF 報告即可包含此紀錄；論文未變更。');}catch(e){message(e.message,true);}});

render();
