const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships',REL='http://schemas.openxmlformats.org/package/2006/relationships',CT='http://schemas.openxmlformats.org/package/2006/content-types';
const elements=(node,name)=>Array.from(node.getElementsByTagNameNS(W,name));
const child=(node,name)=>Array.from(node.children).find(n=>n.namespaceURI===W&&n.localName===name);
const attr=(node,name)=>node?.getAttributeNS(W,name)??'';
const parse=text=>{if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('不支援含自訂 XML 實體的文件。');const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw Error('Word 內部資料損毀，請在 Word 重新另存。');return doc;};
const xml=doc=>new XMLSerializer().serializeToString(doc);
const orders={pPr:['pStyle','keepNext','keepLines','pageBreakBefore','framePr','widowControl','numPr','suppressLineNumbers','pBdr','shd','tabs','suppressAutoHyphens','kinsoku','wordWrap','overflowPunct','topLinePunct','autoSpaceDE','autoSpaceDN','bidi','adjustRightInd','snapToGrid','spacing','ind','contextualSpacing','mirrorIndents','suppressOverlap','jc','textDirection','textAlignment','textboxTightWrap','outlineLvl','divId','cnfStyle','rPr','sectPr','pPrChange'],rPr:['rStyle','rFonts','b','bCs','i','iCs','caps','smallCaps','strike','dstrike','outline','shadow','emboss','imprint','noProof','snapToGrid','vanish','webHidden','color','spacing','w','kern','position','sz','szCs','highlight','u','effect','bdr','shd','fitText','vertAlign','rtl','cs','em','lang','eastAsianLayout','specVanish','oMath','rPrChange'],sectPr:['headerReference','footerReference','footnotePr','endnotePr','type','pgSz','pgMar','paperSrc','pgBorders','lnNumType','pgNumType','cols','formProt','vAlign','noEndnote','titlePg','textDirection','bidi','rtlGutter','docGrid','printerSettings','sectPrChange']};
function ensure(node,name){let el=child(node,name);if(el)return el;el=node.ownerDocument.createElementNS(W,'w:'+name);const order=orders[node.localName];if(order){const index=order.indexOf(name),next=Array.from(node.children).find(n=>order.indexOf(n.localName)>index);node.insertBefore(el,next||null);}else if(name==='pPr'||name==='rPr')node.insertBefore(el,node.firstChild);else node.append(el);return el;}
function set(node,name,value){if(attr(node,name)===String(value))return false;node.setAttributeNS(W,'w:'+name,String(value));return true;}
export async function openDocx(bytes){let zip;try{zip=await JSZip.loadAsync(bytes);}catch{throw Error('無法開啟 Word 檔案，請確認為未加密的 .docx。');}const files=Object.values(zip.files);if(files.length>5000||files.reduce((s,f)=>s+(f._data?.uncompressedSize||0),0)>180*1024*1024)throw Error('解壓縮後檔案過大，請先壓縮論文圖片。');if(!zip.file('word/document.xml')||!zip.file('[Content_Types].xml'))throw Error('這不是有效的 .docx 論文。');return zip;}
export async function inspectDocx(zip){const doc=parse(await zip.file('word/document.xml').async('string'));const paragraphs=elements(doc,'p').map((p,index)=>({index,text:elements(p,'t').map(t=>t.textContent).join('')}));let start=paragraphs.find(p=>/^(第[一壹1１]章|Chapter\s+1(?:\s|[.:：])|1[.、．\s]+(?:緒論|前言|Introduction))/i.test(p.text.trim())&&!/[.．…]{2}|\t/.test(p.text));return{paragraphs,start:start?.index??-1};}
export function readRequirement(raw){const t=raw.normalize('NFKC').replace(/\s+/g,' ').replace(/(\p{Script=Han})\s+(?=\p{Script=Han})/gu,'$1');const rules={};const put=(key,value,evidence)=>{rules[key]={value:String(value),enabled:true,evidence:'原文：'+evidence.trim().slice(0,140)};};
const unique=(key,matches,convert=m=>m[1])=>{const values=matches.map(convert);if(new Set(values).size===1&&matches.length)put(key,values[0],matches[0][0]);};
if(/A4/i.test(t)&&!/(?:A3|Letter|B5)/i.test(t))put('paper','A4',t.match(/.{0,15}A4.{0,28}/i)[0]);
const unit='(?:公分|厘米|cm|centimeters?|吋|英吋|inches?|mm|毫米)';const amount='(\\d+(?:\\.\\d+)?)';
const cm=m=>{const u=m[2].toLowerCase();return +(Number(m[1])*(/吋|inch/.test(u)?2.54:/mm|毫米/.test(u)?.1:1)).toFixed(3);};
for(const [key,label,en] of [['top','上','top'],['bottom','下','bottom'],['left','左','left'],['right','右','right']]){const re=new RegExp(`(?:${label}(?:方|邊界|邊距|側)?|${en}(?: margin)?)[\\s:：為各]*${amount}\\s*(${unit})`,'gi');unique(key,[...t.matchAll(re)],cm);}
for(const [pair,keys] of [['左右',['left','right']],['上下',['top','bottom']]]){const matches=[...t.matchAll(new RegExp(`${pair}(?:邊界|邊距)?[\\s各為:：]*${amount}\\s*(${unit})`,'gi'))];for(const key of keys){const label={left:'左',right:'右',top:'上',bottom:'下'}[key];const individual=[...t.matchAll(new RegExp(`(?:${label}(?:方|邊界|邊距|側)?|${key}(?: margin)?)[\\s:：為各]*${amount}\\s*(${unit})`,'gi'))];delete rules[key];unique(key,[...individual,...matches],cm);}}
const fontPatterns={cjk:/(?:中文|中文字[型體]?)[^。；;]{0,24}?(標楷體|新細明體|細明體|微軟正黑體|宋體|黑體)/g,latin:/(?:英文|英文字[型體]?)[^。；;]{0,30}?(Times\s+New\s+Roman|Arial|Calibri)/gi};for(const [key,re]of Object.entries(fontPatterns))unique(key,[...t.matchAll(re)],m=>m[1].replace(/\s+/g,' '));
// Cover and title font sizes do not become body font requirements.
const clauses=t.split(/[。；;]/).filter(s=>/本文|正文|body|中文.*英文/i.test(s));const sizes=[];for(const clause of clauses)sizes.push(...clause.matchAll(/(\d+(?:\.\d+)?)\s*(?:號|pt\b|點)/gi));unique('size',sizes,m=>Number(m[1]));
unique('line',[...t.matchAll(/(\d+(?:\.\d+)?)\s*(?:倍)?行距/g)],m=>Number(m[1]));if(!rules.line&&/雙倍行距|double[- ]spac/i.test(t))put('line',2,'雙倍行距');
if(/(?:顏色為|字[體色]為?|文字顏色)[\s:：]*(?:黑色|黑)/.test(t))put('color','黑色',t.match(/.{0,12}(?:顏色為|字[體色]為?|文字顏色)[\s:：]*(?:黑色|黑).{0,12}/)[0]);
if(/(?:各頁|每頁)[^。]{0,12}(?:正下方|下方中央)[^。]{0,12}(?:頁數|頁碼)|頁碼[^。]{0,20}(?:頁尾置中|下方置中|底端置中|下方中央)/.test(t))put('page','頁尾置中',t.match(/[^。]{0,15}(?:正下方|下方中央|頁尾置中|下方置中|底端置中)[^。]{0,20}/)[0]);return rules;}
export async function formatDocx(bytes,settings,start,{preview=false}={}){const zip=await openDocx(bytes),doc=parse(await zip.file('word/document.xml').async('string')),paragraphs=elements(doc,'p');if(!Number.isInteger(start)||start<0||start>=paragraphs.length)throw Error('正文起始段落不正確。');const originalText=elements(doc,'t').map(n=>n.textContent).join('\u0000');const originalFormula=Array.from(doc.getElementsByTagNameNS('http://schemas.openxmlformats.org/officeDocument/2006/math','oMath')).map(xml).join('');const changes=[],warnings=[],locations=[],counts={font:0,size:0,color:0,line:0};const styles=zip.file('word/styles.xml')?parse(await zip.file('word/styles.xml').async('string')):null;
const styleMap=new Map(styles?elements(styles,'style').map(s=>[attr(s,'styleId'),s]):[]);function specialStyle(id,seen=new Set()){if(!id||seen.has(id))return false;seen.add(id);const s=styleMap.get(id);if(/heading|title|caption|toc|標題|标题|圖說|图说/i.test(id+' '+attr(s&&child(s,'name'),'val')))return true;if(s&&elements(s,'outlineLvl').some(n=>Number(attr(n,'val'))<9))return true;return s?specialStyle(attr(child(s,'basedOn'),'val'),seen):false;}
const hasAncestor=(p,name)=>{let node=p.parentElement;while(node){if(node.namespaceURI===W&&node.localName===name)return true;node=node.parentElement;}return false;};let skipped=0,eligible=0;
for(let i=start;i<paragraphs.length;i++){const p=paragraphs[i],text=elements(p,'t').map(t=>t.textContent).join(''),pp=child(p,'pPr');if(!text.trim())continue;const ps=attr(pp&&child(pp,'pStyle'),'val');if(hasAncestor(p,'tbl')||hasAncestor(p,'txbxContent')||specialStyle(ps)||(pp&&elements(pp,'outlineLvl').some(n=>Number(attr(n,'val'))<9))||/^(第[一二三四五六七八九十百壹貳參\d]+[章節]|Chapter\s+\d+|[圖表]\s*\d|Figure\s*\d|Table\s*\d|摘要$|Abstract$|參考文獻$)/i.test(text.trim())||elements(p,'drawing').length||p.getElementsByTagNameNS('http://schemas.openxmlformats.org/officeDocument/2006/math','oMath').length||elements(p,'instrText').length||elements(p,'fldSimple').length){skipped++;continue;}eligible++;const previousCounts={...counts};if(settings.line!==undefined){const pr=ensure(p,'pPr'),spacing=ensure(pr,'spacing');let changed=set(spacing,'line',Math.round(settings.line*240));changed=set(spacing,'lineRule','auto')||changed;changed=set(ensure(pr,'snapToGrid'),'val','0')||changed;if(changed)counts.line++;}
for(const r of elements(p,'r')){if(!elements(r,'t').length||hasAncestor(r,'del')||elements(r,'fldChar').length)continue;const pr=ensure(r,'rPr');if(settings.cjk||settings.latin){const f=ensure(pr,'rFonts');let changed=false;for(const [name,value]of [['eastAsia',settings.cjk],['ascii',settings.latin],['hAnsi',settings.latin]])if(value){changed=set(f,name,value)||changed;const theme=name==='eastAsia'?'eastAsiaTheme':name+'Theme';if(f.hasAttributeNS(W,theme)){f.removeAttributeNS(W,theme);changed=true;}}if(changed)counts.font++;}if(settings.size){let changed=set(ensure(pr,'sz'),'val',Math.round(settings.size*2));changed=set(ensure(pr,'szCs'),'val',Math.round(settings.size*2))||changed;if(changed)counts.size++;}if(settings.color){const color=ensure(pr,'color');let changed=set(color,'val','000000');for(const a of ['themeColor','themeTint','themeShade'])if(color.hasAttributeNS(W,a)){color.removeAttributeNS(W,a);changed=true;}if(changed)counts.color++;}}
const affected=Object.keys(counts).filter(k=>counts[k]>previousCounts[k]).map(k=>({font:'字型',size:'字級',color:'文字顏色',line:'行距'})[k]);if(affected.length)locations.push(`第 ${i+1} 個段落「${text.slice(0,70)}${text.length>70?'…':''}」：${affected.join('、')}。`);
}
if(counts.font)changes.push(`字型：${[settings.cjk&&'中文 '+settings.cjk,settings.latin&&'英文 '+settings.latin].filter(Boolean).join('；')}。調整 ${counts.font} 個文字片段。`);if(counts.size)changes.push(`本文字級：${settings.size} pt。調整 ${counts.size} 個文字片段。`);if(counts.color)changes.push(`本文文字改為黑色：${counts.color} 個文字片段。`);if(counts.line)changes.push(`本文 ${settings.line} 倍行距，關閉段落對齊格線：${counts.line} 個段落。`);
const allSections=elements(doc,'sectPr').filter(s=>!hasAncestor(s,'sectPrChange'));const sections=allSections.filter(s=>{const p=s.parentElement?.localName==='pPr'?s.parentElement.parentElement:null;return !p||paragraphs.indexOf(p)>=start;});let paperCount=0,marginCount=0;const twips=cm=>Math.round(cm/2.54*1440);for(const s of sections){const beforePaper=paperCount,beforeMargin=marginCount;if(settings.paper){const size=ensure(s,'pgSz'),dims=settings.paper==='A4'?[11906,16838]:[12240,15840];let changed=set(size,'w',dims[0]);changed=set(size,'h',dims[1])||changed;if(attr(size,'orient')==='landscape'){size.removeAttributeNS(W,'orient');changed=true;}if(changed)paperCount++;}let changed=false;for(const key of ['top','bottom','left','right'])if(settings[key]!==undefined)changed=set(ensure(s,'pgMar'),key,twips(settings[key]))||changed;if(changed)marginCount++;if(paperCount>beforePaper||marginCount>beforeMargin)locations.push(`第 ${allSections.indexOf(s)+1} 節：${[paperCount>beforePaper?'紙張大小／方向':'',marginCount>beforeMargin?'頁面邊界':''].filter(Boolean).join('、')}（此節全部頁面）。`);}
if(paperCount)changes.push(`紙張：${settings.paper} 直向，調整 ${paperCount} 個節。`);if(marginCount)changes.push(`頁面邊界：${[['top','上'],['bottom','下'],['left','左'],['right','右']].filter(([k])=>settings[k]!==undefined).map(([k,n])=>n+' '+settings[k]+' 公分').join('、')}，調整 ${marginCount} 個節。`);
if(settings.page){const relPath='word/_rels/document.xml.rels';const rels=zip.file(relPath)?parse(await zip.file(relPath).async('string')):parse(`<Relationships xmlns="${REL}"/>`);const types=parse(await zip.file('[Content_Types].xml').async('string'));let inserted=0,aligned=0,footerId=1;for(const section of sections){for(const type of ['default','first','even']){if(type==='first'&&!child(section,'titlePg'))continue;if(type==='even'){const st=zip.file('word/settings.xml')?await zip.file('word/settings.xml').async('string'):'';if(!/evenAndOddHeaders/.test(st))continue;}let ref=elements(section,'footerReference').find(n=>attr(n,'type')===type);if(!ref){const sectionIndex=allSections.indexOf(section);for(let i=sectionIndex-1;i>=0&&!ref;i--)ref=elements(allSections[i],'footerReference').find(n=>attr(n,'type')===type);}const beforeFooter=inserted+aligned;let footer=null,oldPath=null;if(ref){const id=ref.getAttributeNS(R,'id');const rel=Array.from(rels.documentElement.children).find(n=>n.getAttribute('Id')===id);if(rel){const target=rel.getAttribute('Target');oldPath=target.startsWith('/')?target.slice(1):'word/'+target.replace(/^\.\//,'');if(zip.file(oldPath))footer=parse(await zip.file(oldPath).async('string'));}if(!footer){warnings.push('部分既有頁尾無法解析，已保留；請在 Word 檢查頁碼。');continue;}}if(!footer)footer=parse(`<w:ftr xmlns:w="${W}"/>`);
// Clone linked footers so untouched front matter retains its own footer.
const pageParagraphs=elements(footer,'p').filter(p=>/\bPAGE\b/i.test(elements(p,'instrText').map(n=>n.textContent).join(''))||elements(p,'fldSimple').some(n=>/\bPAGE\b/i.test(attr(n,'instr'))));if(pageParagraphs.length){for(const p of pageParagraphs)if(set(ensure(ensure(p,'pPr'),'jc'),'val','center'))aligned++;}else{const p=footer.createElementNS(W,'w:p');footer.documentElement.append(p);set(ensure(ensure(p,'pPr'),'jc'),'val','center');const field=footer.createElementNS(W,'w:fldSimple');set(field,'instr',' PAGE ');set(field,'dirty','true');p.append(field);const r=footer.createElementNS(W,'w:r');const t=footer.createElementNS(W,'w:t');t.textContent='1';r.append(t);field.append(r);inserted++;}
if(inserted+aligned>beforeFooter)locations.push(`第 ${allSections.indexOf(section)+1} 節，${({default:'一般',first:'首頁',even:'偶數頁'})[type]}頁尾：${pageParagraphs.length?'既有頁碼置中':'新增置中頁碼'}。`);
while(zip.file(`word/thesisFooter${footerId}.xml`))footerId++;const path=`word/thesisFooter${footerId}.xml`;let id=`rIdThesis${footerId}`;while(Array.from(rels.documentElement.children).some(n=>n.getAttribute('Id')===id))id+='x';footerId++;zip.file(path,xml(footer));if(oldPath){const oldRels=oldPath.replace(/([^/]+)$/,'_rels/$1.rels');if(zip.file(oldRels))zip.file(path.replace(/([^/]+)$/,'_rels/$1.rels'),await zip.file(oldRels).async('uint8array'));}const rel=rels.createElementNS(REL,'Relationship');rel.setAttribute('Id',id);rel.setAttribute('Type',R+'/footer');rel.setAttribute('Target',path.slice(5));rels.documentElement.append(rel);const over=types.createElementNS(CT,'Override');over.setAttribute('PartName','/'+path);over.setAttribute('ContentType','application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml');types.documentElement.append(over);let direct=elements(section,'footerReference').find(n=>attr(n,'type')===type);if(!direct){direct=doc.createElementNS(W,'w:footerReference');section.insertBefore(direct,Array.from(section.children).find(n=>!['headerReference','footerReference'].includes(n.localName))||null);set(direct,'type',type);}direct.setAttributeNS(R,'r:id',id);
}}zip.file(relPath,xml(rels));zip.file('[Content_Types].xml',xml(types));if(inserted)changes.push(`新增頁尾置中的自動頁碼：${inserted} 個頁尾（保留原有頁尾內容）。`);if(aligned)changes.push(`既有頁碼改為置中：${aligned} 個頁尾段落。`);if(inserted||aligned)warnings.push('保留原節的頁碼起算與數字格式；若正文需重新從 1 起算或前言使用羅馬數字，請在 Word 檢查。既有頁首頁碼不會移除。');}
if(zip.file('word/settings.xml')){const st=parse(await zip.file('word/settings.xml').async('string'));if(set(ensure(st.documentElement,'updateFields'),'val','true'))changes.push('設定 Word 開啟檔案時要求更新欄位；仍需在 Word 確認目錄與頁碼。');zip.file('word/settings.xml',xml(st));}
if(elements(doc,'t').map(n=>n.textContent).join('\u0000')!==originalText||Array.from(doc.getElementsByTagNameNS('http://schemas.openxmlformats.org/officeDocument/2006/math','oMath')).map(xml).join('')!==originalFormula)throw Error('內容完整性檢查未通過，已停止輸出。');zip.file('word/document.xml',xml(doc));
warnings.push(`文字格式處理範圍：第 ${start+1} 個段落起的 ${eligible} 個一般段落；保留 ${skipped} 個標題、表格、圖說、公式或欄位段落的原格式。`);if(start>0)warnings.push('頁面設定以「節」為單位；正文起點與前置頁若屬同一節，該節全部頁面會一併套用。');if(elements(doc,'ins').length||elements(doc,'del').length)warnings.push('文件含追蹤修訂，已保留；建議在 Word 確認修訂狀態。');warnings.push('字型須在開啟檔案的電腦上安裝，否則 Word 可能代換字型。橫向跨頁、圖表寬度及特殊章節請另行確認。');if(preview)return{changes,warnings,locations};const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',compression:'DEFLATE',compressionOptions:{level:6}});return{blob,changes,warnings,locations};}
