import {getAIContext} from './app.js?v=20260921-format5';
import {referenceStart,referenceRows} from './ai-core.js?v=20260921-format5';
import {reportHTML,exportPDF} from './ai-report.js?v=20260921-format5';
const $=id=>document.getElementById(id);let rows=[],page=0,external=null,sourceDoc=null,loadVersion=0;
function status(text){$('refcheck-status').textContent=text;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function render(){const pages=Math.max(1,rows.length);page=Math.min(page,pages-1);$('refcheck-preview').textContent=rows[page]?.text||'尚未擷取；請先上傳 Word，再指定參考文獻標題。';$('refcheck-count').textContent=`${rows.length} 個非空書目段落 · ${rows.length?page+1:0} / ${rows.length} 段`;for(const id of ['refcheck-copy','refcheck-txt'])$(id).disabled=!rows.length;$('refcheck-prev').disabled=page===0;$('refcheck-next').disabled=page>=pages-1;for(const id of ['refcheck-html','refcheck-pdf'])$(id).disabled=!external;$('refcheck-imported').textContent=external?`已匯入 ${external.fileName}｜${external.importedAt}；使用者提供，尚未獨立驗證。`:'尚未匯入 RefCheck 結果。';}
function extract(){const ctx=getAIContext();rows=ctx.thesis?referenceRows(ctx.thesis.info.paragraphs,Number($('refcheck-start').value)):[];sourceDoc=ctx.thesis;page=0;render();status('擷取僅在本機進行；請逐段檢視，跨段或辨識錯誤的文獻請在 RefCheck 貼上後確認。');}
$('open-refcheck').addEventListener('click',()=>{const ctx=getAIContext(),select=$('refcheck-start'),previous=select.value;select.replaceChildren(new Option('請指定參考文獻標題所在段落','-1'));for(const p of ctx.thesis?.info.paragraphs||[])if(p.text.trim())select.add(new Option(`${p.index+1} · ${p.text.slice(0,70)}`,String(p.index)));select.value=sourceDoc===ctx.thesis&&previous?previous:String(referenceStart(ctx.thesis?.info.paragraphs||[]));extract();$('refcheck-dialog').showModal();});
$('refcheck-start').addEventListener('change',extract);$('refcheck-prev').addEventListener('click',()=>{page--;render();});$('refcheck-next').addEventListener('click',()=>{page++;render();});
$('refcheck-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(rows.map(r=>r.text).join('\n\n'));status('參考文獻已複製。請到 RefCheck 的 Paste Text 貼上，檢視擷取結果後再開始驗證。');}catch{status('無法存取剪貼簿，請下載 TXT 後自行貼上或上傳。');}});
$('refcheck-txt').addEventListener('click',()=>download(new Blob(['\ufeff'+rows.map(r=>r.text).join('\n\n')],{type:'text/plain;charset=utf-8'}),'參考文獻_供RefCheck檢查.txt'));
$('refcheck-file').addEventListener('change',async()=>{const file=$('refcheck-file').files[0],ctx=getAIContext(),version=++loadVersion;if(!file)return;try{if(!ctx.thesis)throw Error('請先上傳 Word，讓外部報告能對應目前論文。');if(!/\.(txt|csv)$/i.test(file.name)||file.size>1024*1024)throw Error('請選擇 RefCheck 下載的 UTF-8 TXT 或 CSV（最大 1 MB）。');const text=(await file.text()).replace(/^\ufeff/,'');if(version!==loadVersion||getAIContext().thesis!==ctx.thesis)return;if(!text.trim()||text.length>100000||text.includes('\u0000'))throw Error('報告內容為空、格式不符或超過 10 萬字元。');external={fileName:file.name,importedAt:new Date().toLocaleString('zh-TW'),text,source:'https://ref-check.org/',thesisName:ctx.thesis.name,origin:'使用者自行匯入的外部報告；來源與內容未經本系統獨立驗證'};document.dispatchEvent(new CustomEvent('refcheck-imported',{detail:external}));status('外部結果已匯入；不會自動配對為論文已通過，亦不修改任何文獻或統計內容。');render();}catch(e){status(e.message);}finally{$('refcheck-file').value='';}});
function externalReport(){return{name:external.thesisName,date:external.importedAt,provider:'未執行本系統 AI',model:'不適用',targetStyle:'不適用',tasks:[],status:'已匯入外部報告，尚待人工覆核；未自動送出或取回',findings:[],rules:[],registry:[],summaries:[],coverage:['本報告僅留存使用者匯入的 RefCheck 結果，未獨立判定任何文獻正確。'],completed:0,planned:0,inputTokens:0,outputTokens:0,externalReview:external};}
$('refcheck-html').addEventListener('click',()=>{if(external)download(new Blob([reportHTML(externalReport())],{type:'text/html;charset=utf-8'}),'RefCheck外部查證紀錄.html');});
$('refcheck-pdf').addEventListener('click',async()=>{if(!external)return;$('refcheck-pdf').disabled=true;try{download(await exportPDF(reportHTML(externalReport()),status),'RefCheck外部查證紀錄.pdf');status('PDF 已下載；外部結果仍需人工核對。');}catch(e){status(e.message);}finally{render();}});
document.addEventListener('thesis-context-changed',()=>{loadVersion++;rows=[];external=null;sourceDoc=null;render();});render();
