import {verifyReference,doiFrom} from './ai-core.js?v=20260921-unified9';
export const DATABASES={crossref:{name:'Crossref',home:'https://search.crossref.org/',mode:'api'},openalex:{name:'OpenAlex',home:'https://openalex.org/',mode:'api'},pubmed:{name:'PubMed',home:'https://pubmed.ncbi.nlm.nih.gov/',mode:'api'},airiti:{name:'華藝線上圖書館',home:'https://www.airitilibrary.com/',mode:'manual'},ndltd:{name:'臺灣博碩士論文知識加值系統',home:'https://ndltd.ncl.edu.tw/',mode:'manual'},wos:{name:'Web of Science',home:'https://www.webofscience.com/',mode:'manual'},scopus:{name:'Scopus',home:'https://www.scopus.com/',mode:'manual'},refcheck:{name:'RefCheck（外部參考工具）',home:'https://ref-check.org/',mode:'manual'},scholar:{name:'Google Scholar',home:'https://scholar.google.com/',mode:'manual'}};
const clean=value=>String(value||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
let lastPubmed=0;
async function fetchJSON(url,signal,key=''){signal?.throwIfAborted();if(url.includes('eutils.ncbi.nlm.nih.gov')){const delay=Math.max(0,400-(Date.now()-lastPubmed));if(delay)await new Promise(resolve=>setTimeout(resolve,delay));signal?.throwIfAborted();lastPubmed=Date.now();}const c=new AbortController(),abort=()=>c.abort(),timer=setTimeout(()=>c.abort(),20000);signal?.addEventListener('abort',abort,{once:true});try{const headers={};if(key){if(new URL(url).origin!=='https://api.openalex.org')throw Error('金鑰端點不符');headers.Authorization='Bearer '+key;}const r=await fetch(url,{signal:c.signal,headers});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(data.error||data.esearchresult?.ERROR)throw Error('資料來源回傳錯誤');return data;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
function candidate(fields){return {doi:'',title:'',authors:[],year:null,journal:'',volume:'',issue:'',pages:'',abstract:'',updates:[],url:'',...fields};}
export async function verifySources(row,signal,{sources=['crossref','openalex','pubmed'],openalexKey=''}={}){const doi=doiFrom(row.text),query=doi||row.text.slice(0,300),checks=[];
 for(const id of sources){if(!DATABASES[id]||DATABASES[id].mode!=='api')continue;signal?.throwIfAborted();let source='';try{let candidates=[],method=doi?'DOI 查詢':'書目文字搜尋';if(id==='crossref'){const r=await verifyReference(row,signal);checks.push({...r,id,database:DATABASES[id].name,mode:'api',outcome:r.status.startsWith('查詢失敗')?'error':r.candidates.length?'found':'not_found'});continue;}
 if(id==='openalex'){const params=new URLSearchParams({'per-page':'3'});if(doi)params.set('filter','doi:https://doi.org/'+doi);else params.set('search',query);source='https://api.openalex.org/works?'+params;const data=await fetchJSON(source,signal,openalexKey);if(!Array.isArray(data.results))throw Error('資料格式錯誤');candidates=data.results.map(m=>candidate({doi:clean(m.doi).replace(/^https?:\/\/doi.org\//i,''),title:clean(m.display_name),authors:(m.authorships||[]).map(a=>clean(a.author?.display_name)),year:m.publication_year,journal:clean(m.primary_location?.source?.display_name),volume:clean(m.biblio?.volume),issue:clean(m.biblio?.issue),pages:[m.biblio?.first_page,m.biblio?.last_page].filter(Boolean).join('-'),url:m.id||'',recordId:m.id||'',retracted:m.is_retracted===true}));}
 if(id==='pubmed'){const term=doi?doi+'[AID]':query;source='https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?'+new URLSearchParams({db:'pubmed',retmode:'json',retmax:'3',term});const data=await fetchJSON(source,signal);if(!Array.isArray(data.esearchresult?.idlist))throw Error('資料格式錯誤');const ids=data.esearchresult.idlist;if(ids.length){const summaryURL='https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?'+new URLSearchParams({db:'pubmed',retmode:'json',id:ids.join(',')});const summary=await fetchJSON(summaryURL,signal);if(!ids.every(id=>summary.result?.[id]))throw Error('書目摘要資料不完整');candidates=ids.map(id=>summary.result[id]).filter(Boolean).map(m=>candidate({doi:clean(m.articleids?.find(a=>a.idtype==='doi')?.value),title:clean(m.title),authors:(m.authors||[]).map(a=>clean(a.name)),year:clean(m.pubdate).match(/\d{4}/)?.[0]||null,journal:clean(m.fulljournalname||m.source),volume:clean(m.volume),issue:clean(m.issue),pages:clean(m.pages),url:'https://pubmed.ncbi.nlm.nih.gov/'+m.uid+'/',recordId:m.uid,metadataSource:summaryURL}));}}
 checks.push({id,database:DATABASES[id].name,mode:'api',outcome:candidates.length?'found':'not_found',status:candidates.length?'找到候選紀錄，仍需核對作者、題名與引用主張':'此來源未找到紀錄；不能據此判定虛假',method,query,source,candidates,checkedAt:new Date().toISOString()});
 }catch(error){if(signal?.aborted)throw new DOMException('已取消','AbortError');checks.push({id,database:DATABASES[id].name,mode:'api',outcome:'error',status:'查詢未完成：'+(/^HTTP \d+$/.test(error.message)?error.message:'連線、逾時或資料解析失敗')+(id==='openalex'?'；可於查證來源填入 OpenAlex 金鑰後重試':''),method:doi?'DOI 查詢':'書目文字搜尋',source,query,candidates:[],checkedAt:new Date().toISOString()});}}
 for(const [id,db]of Object.entries(DATABASES).filter(([,db])=>db.mode==='manual'))checks.push({id,database:db.name,mode:'manual',outcome:'manual_pending',status:'尚待人工查證；提供入口不代表已完成查詢',method:'人工查證入口',source:db.home,query,candidates:[],checkedAt:null});
 const candidates=checks.flatMap(c=>c.candidates.map(item=>({...item,database:c.database}))),found=checks.filter(c=>c.outcome==='found').length,failed=checks.filter(c=>c.outcome==='error').length;
 return{...row,checks,candidates,status:`${found} 個來源找到候選紀錄；${failed} 個來源查詢未完成；人工來源待確認`,source:checks[0]?.source||'',method:'多來源書目核對',checkedAt:new Date().toISOString()};
}
export function saveManualCheck(check,{url,status,note}){if(!['matched','mismatch','not_found','unavailable'].includes(status))throw Error('請選擇人工查證結果。');let link;try{link=new URL(url);}catch{throw Error('請填入實際查證的官方網址。');}const home=new URL(DATABASES[check.id].home).hostname.replace(/^www\./,'');if(!['https:','http:'].includes(link.protocol)||!(link.hostname===home||link.hostname.endsWith('.'+home)))throw Error('請使用所選資料庫的官方紀錄或查詢網址。');if(link.username||link.password||/[?&](api_key|key|token|access_token)=/i.test(link.href))throw Error('網址不可含帳密或金鑰。');if(!note.trim()||note.length>2000||url.length>2000)throw Error('請填入查證依據（最多 2,000 字）。');const labels={matched:'使用者確認書目相符（未驗證全文主張）',mismatch:'使用者發現書目不符，需人工修正',not_found:'使用者查無紀錄，不能判定虛假',unavailable:'使用者無法存取或完成查證'};check.manual={status,label:labels[status],url:link.href,note:note.trim(),checkedAt:new Date().toISOString(),origin:'使用者自行登錄；系統未獨立驗證'};return check.manual;}
